### ISSUE TITLE
Search doesn't reveal carbon emissions tap

### ISSUE THREAD

**Issue by sbalnojan** [meltano/hub#1006]
The search on the hub doesn't show me anything for the carbon emissions tap regardless of what I type in. Any ideas?

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/43072233/201954428-20c89432-06b9-442c-b496-dbe68ee4c9df.png">

**Comment by pnadolny13** [comment]
@sbalnojan I suspect thats what happens when we add the `hidden` key to the plugin definition https://github.com/meltano/hub/blob/8a3dece0f6e4e4b655e8ec57cf501d2e963e2732/_data/meltano/extractors/tap-carbon-intensity/meltano.yml#L7. I dont know the exact reason for this being hidden though, maybe because its still in the old gitlab organization.

**Comment by sbalnojan** [comment]
That makes sense :-) I'm looking for a good demo API that doesn't require authentification. This one would qualify, but I would rather choose one that is well maintained. Do you have suggestions?

**Comment by aaronsteers** [comment]
@pnadolny13, @sbalnojan - I've also had the same question frequently.

I went through the full list of extractors just now and found the ones I mostly would lean to:

- https://hub.meltano.com/extractors/tap-csv/ - generic CSV
- https://hub.meltano.com/extractors/tap-spreadsheets-anywhere/ - generic connector that can use data from webpages and other public sheets/resources/files on the web
- https://hub.meltano.com/extractors/tap-feed/ - generic RSS
- https://hub.meltano.com/extractors/tap-stackoverflow-sampledata/ - a large dataset, created for perf tests but probably has lots of interesting use cases 
- https://hub.meltano.com/extractors/tap-github/ - lowest tier of rate limit doesn't require auth token
- https://hub.meltano.com/extractors/tap-meltanohub/ - the most meta extractor

"Fun" ones:

- https://hub.meltano.com/extractors/tap-rickandmorty/ - I also have a fork of this somewhere if the listed one isn't working.
- https://hub.meltano.com/extractors/tap-lotr/ - lord of the rings

This one looks cool but needs an update on the hub to define settings:

- https://github.com/loeakaodas/tap-open-library

I don't know enough of their API pricing to confidently promote this but in theory this opens a lot of potentially interesting applications, the API has a free tier as well as a paid tier:

- https://github.com/Matatika/tap-openweathermap

@pnadolny13, @sbalnojan - Can we add a keyword for 'no-auth-required' or `easy-setup` or `popular-for-demos` or similar, so they can all be surfaces in a single search on the hub?

**Comment by sbalnojan** [comment]
@aaronsteers tapping csv sounds sooo not cool for the demo :-) But yes I've thought about them as well. I'll check out the others and choose one. Leaning very much towards the Meltanohub one because I really don't want this to break. In the long run I think we should simply provide an API + tap ourselves, but seems like its not needed now.

Thanks for the list! I'll find something useful. And of course this issue can be closed unless you want to add something.

**Comment by edgarrmondragon** [comment]
https://anapioficeandfire.com/Documentation is another API that doesn't require auth and seems fun and simple

**Comment by aaronsteers** [comment]
> [anapioficeandfire.com/Documentation](https://anapioficeandfire.com/Documentation) is another API that doesn't require auth and seems fun and simple

Super fun! Thanks for the info - this looks cool.

![image](https://user-images.githubusercontent.com/18150651/203481301-84844f4e-175b-42b2-a69b-394f16e485f7.png)
