### ISSUE TITLE
Search keywords for "no auth", "easy setup", and/or "easy demo" extractors

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#1010]
_Originally posted by @aaronsteers in https://github.com/meltano/hub/issues/1006#issuecomment-1315725058_

> Can we add a keyword to these so they can all be surfaced in a single search on the hub? Something like `no-auth-required` or `easy-setup` or `popular-demos` or similar?

We often want to find extractors that are one of the below:

1. Zero-config - a connector that 'just works' without needing any config.
   - The extractor might accept config, but it does some kind of sync operation even with zero config.
   - Examples: `tap-carbonintensity`, `tap-meltanohub`
1. Zero-auth - connectors that can work without any secrets management backend.
   - Examples: `tap-csv`, `tap-spreadsheets-anywhere`, plus all the above in `zero-config`.
3. "Free" auth key, and therefore easily demoable.
   - Might require an API auth key but doesn't require paid membership.
   - Might require a paid API auth for higher rate limits.
   - Examples: `tap-github`, `tap-open-library`, `tap-openweathermap`, plus all of the above in `zero-config` and `zero-auth`.

I'm open to different names here, but some proposed keywords we could use are:

- `zero auth`
- `zero config`
- `free service`

@tayloramurphy, @pnadolny13, @sbalnojan - what do you think about a path forward here?

--------------------------

From https://github.com/meltano/hub/issues/1006#issuecomment-1315725058

I went through the full list of extractors just now and found the ones I mostly would lean to:

- https://hub.meltano.com/extractors/tap-csv/ - generic CSV
- https://hub.meltano.com/extractors/tap-spreadsheets-anywhere/ - generic connector that can use data from webpages and other public sheets/resources/files on the web
- https://hub.meltano.com/extractors/tap-feed/ - generic RSS
- https://hub.meltano.com/extractors/tap-stackoverflow-sampledata/ - a large dataset, created for perf tests but probably has lots of interesting use cases 
- https://hub.meltano.com/extractors/tap-github/ - lowest tier of rate limit doesn't require auth token
- https://hub.meltano.com/extractors/tap-meltanohub/ - the most meta extractor

"Fun" ones:

- https://hub.meltano.com/extractors/tap-rickandmorty/ - I also have a fork of this somewhere if the listed one isn't working.
- https://hub.meltano.com/extractors/tap-lotr/ - lord of the rings

This one looks cool but needs an update on the hub to define settings:

- https://github.com/loeakaodas/tap-open-library

I don't know enough of their API pricing to confidently promote this but in theory this opens a lot of potentially interesting applications, the API has a free tier as well as a paid tier:

- https://github.com/Matatika/tap-openweathermap

**Comment by sbalnojan** [comment]
@aaronsteers 
I feel "zero auth" is a bit misleading. Or maybe we need a different category. I mean the label makes sense, just that I am often looking for a true "API without auth" label. 

We already have the "keywords" functionality although it doesn't seem to be used that often. 

So a path forward should include a "definition" we could put into the hub of a few keywords. We could figure out 4 different keywords we want to use, (the ones you have above and something like API without auth) and then start labeling...
