### ISSUE TITLE
Reformat All Yaml To Pass Linting

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1021]
After https://github.com/meltano/hub/pull/979 was merged we're getting CI test failures due to existing formatting violations. We should limit the amount of work that everyone has to do piece meal by doing a giant reformat of all yaml files at once.

cc @edgarrmondragon

**Comment by edgarrmondragon** [comment]
Agreed, it's a shame that https://github.com/opt-nc/yamlfixer doesn't do what we need since it's supposed to work in tandem with yamllint.
