### ISSUE TITLE
[Singer Tap/Target] tap-messagebird

### ISSUE THREAD

**Issue by visch** [meltano/hub#1049]
### Description

An omnichannel communications platform, built for global scale

### Entity URL

https://www.messagebird.com/

### Name

messagebird

### Singer Name

tap-messagebird

PR Incoming

**Comment by pnadolny13** [comment]
@visch I added this as part of [this](https://github.com/meltano/hub/pull/1047/files#diff-80e1fe0b3811d753ae8cc36bd3d12af89cfd6a2f706d8fc3066c1282691b69b7) draft PR. I labeled it as "development" but we can toggle that if its ready to be used.

**Comment by visch** [comment]
> @visch I added this as part of [this](https://github.com/meltano/hub/pull/1047/files#diff-80e1fe0b3811d753ae8cc36bd3d12af89cfd6a2f706d8fc3066c1282691b69b7) draft PR. I labeled it as "development" but we can toggle that if its ready to be used.

Nice! Just left a quick review. It's "ready" folks will probably want state support but it should be good enough for some use cases :D

**Comment by pnadolny13** [comment]
@visch nice thanks I can pull those changes into the PR. Also for the description updates, can you update them in the tap itself? This metadata was pulled using `--about` so having the tap be the source of truth would be ideal.
