### ISSUE TITLE
bug: Plugin test CI job doesnt use executable if set

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1066]
If we override the executable the CI job should use it over the plugin name. We do this sometimes when multiple connectors exist with different names in order to consolidate them under one naming convention i.e. tap-tableau and tap-tableau-server both go by the plugin name tap-tableau.

**Comment by edgarrmondragon** [comment]
Maybe a duplicate of https://github.com/meltano/hub/issues/960?

**Comment by pnadolny13** [comment]
@edgarrmondragon thanks I didnt see that one. I'll close this.
