### ISSUE TITLE
bug: api builds fail in CI test

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1093]
See https://github.com/meltano/hub/actions/runs/3714855163/jobs/6299309644 as an example. It looks like we might be passing the wrong inputs or something to the script.

cc @edgarrmondragon since I know you recently worked on this with the new API backend

**Comment by edgarrmondragon** [comment]
@pnadolny13 It's failing for forks because we rely on repo secrets. I could disable the workflow on forks.

**Comment by pnadolny13** [comment]
@edgarrmondragon ah thanks I probably should have guessed that. Its up to you but yeah disabling for forks makes sense to me.
