### ISSUE TITLE
Automate metadata refresh for SDK plugins

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1095]
What:
- We should have an automated process that checks the `--about` output of SDK based plugins and refreshes the hub definition. 

Why:
- Since we prefer SDK based variants and know that they have better stability and better levels of maintenance, we should also be sure that the metadata is always accurate on the hub. We rely on user to update these today which allows some to get out of sync and unchecked.
- Bad settings and metadata can cause the plugin not to work in meltano, so I think this is an important thing to be maintaining.
- This also encourages plugin developer to put their documentation in that plugin repo itself as the SSOT and let the hub scrape it.

How:
- It can run daily/weekly to guarantee the metadata we publish about SDK based variants are good. I created this script https://github.com/pnadolny13/hub-utils that does the core of this translation already.

Challenges:
- I found some functioning taps that fail during help/about so those would have to be skipped
- python version limitations would have to be considered. Some of our CI tests fail to extract about metadata because the python version of the test container isnt supported by the tap.

**Comment by aaronsteers** [comment]
I love this idea. I think it's save to skip those plugins which fail in `--about` for some reason. It could also be helpful to have a list of those and even open an issue on all repos for which `--about` cannot complete.

In an early version of the SDK, some taps or targets could not complete execution of `--about` unless valid config was provided, but in more recent version this should not be an issue.

Another benefit of automating this, is that we can give developers the option to link their README.md back to the Hub "for the latest settings documentation". This could complement or replace their own `settings` list which periodically need to be updated manually via markdown edits.

**Comment by pnadolny13** [comment]
I spent a little time thinking about how this process could work for updating SDK variants and since its relatively similar for Airbyte variants too I want to consider them in this also. I proved out that I can:

1. iterate all existing hub plugins and find a list thats SDK based
2. install the executable via pipx and run --about
3. translate the --about output to the hub definition spec
4. merge the existing definition and the newly exported --about output i.e. updating the existing definition in the hub repo

### Challenges:

1. The install/--about process is pretty slow since we already have ~130 SDK variants
2. Translating --about to the hub definition spec can have edge cases that I dont know about yet. It also requires me to be opinionated about things like sort ordering so that the diffs are consistent between runs. For example I chose to sort the settings list of dicts in alpha order using the name key. 
3. Failures are somewhat frequent ~25/130 failed on my first iteration.
4. Some failures are related to python versions
5. Some failures are due to required configs or credentials for discovery.
6. Airbyte variants require docker 

### Considerations:
- Extracting and translating the --about output on the fly was feeling like ETL vs ELT so I'm hoping to design a process that saves the raw --about output which allows us to iterate on our translation logic and quickly fix any bugs that we notice.
- The raw output has more package and SDK version information in it that might be helpful to keep track of even though we dont currently use it in the hub definition.

### Potential Solution: GitHub Action Similar to Dependabot
1. Get a list of all variants that are SDK based
2. Create a branch
3. Iteratively install and pipe the --about output to files for all variants in the list generated in step 1
4. Iteratively translate all raw --about files into Hub definition spec, merge with whats exists (e.g. if descriptions only exist on the hub then dont overwrite them with null descriptions from --about, etc.).
5. Create a commit for each update, allowing easy reverting of specific updates for the PR reviewer if needed.
6. Collect a list of failed variants
7. Rerun the failed subset on different python versions to see if that was the issue and burn down the list further
8. Open a PR with all definition updates that were made.
9. Pat reviews and merges probably running on a once per week cadence

### Other things I considered:
- This would commit raw --about data to the hub repo. I'm not sure if there are reasons to avoid this other than clutter potentially. Alternative solutions can load them to S3/Snowflake/ or commit to the hub_utils repo (almost acting like the dbt hubcap repo that manages their hub) so only the translated data exists in the hub repo.
- I played with the idea of making a tap that did this extract --about process and wrote to snowflake but that adds challenges for running multiple python versions and running Docker in Docker for Airbyte variants. Both of those are supported on github actions but not in Squared.

@tayloramurphy @aaronsteers @sbalnojan any thoughts?

**Comment by tayloramurphy** [comment]
@pnadolny13 overall your iterative process makes sense. I think you could probably just start even smaller if you wanted and get this up and running with the top 10 most used SDK-connectors and then add more from there. Might be quicker to get the end to end updated and running on a few connectors and then add more too it.

The translation step does seem like something we'd want to obviate at some point though. I'm guessing that we have richer data coming from the SDK than we have on the Hub? As you're doing this, be thinking about how we could unify the two definitions and open or flag any relevant issues.

**Comment by aaronsteers** [comment]
@pnadolny13 - I like this a lot. Thanks for putting so much thought and energy into this.

Since the process is expensive, what about storing the output from --about into S3? We could do that right away, and then get to a second step for exactly how to apply it back to the repo. For failed executions or failed installations, you could instead save a record of the error text.

In subsequent executions, we could bias towards rerunning tests just for failed connectors, or just for connectors with no test result.


The second step, which is to apply the changes back to the repo, is not computationally expensive but it's much more difficult logic-wise. It would be nice to try a few things, and perhaps prioritize the top-10 by usage or other subsets (top 10 by failure rate) when it comes to applying those updates back to the source-controlled yaml files.

Wdyt?

**Comment by pnadolny13** [comment]
> @pnadolny13 overall your iterative process makes sense. I think you could probably just start even smaller if you wanted and get this up and running with the top 10 most used SDK-connectors and then add more from there. Might be quicker to get the end to end updated and running on a few connectors and then add more too it.

@tayloramurphy good point, I can start with a subset for now. At this point though I'm trying to make sure I design it in a way where all by bases are covered once I turn it on for all of them, including Airbyte.

> The translation step does seem like something we'd want to obviate at some point though. I'm guessing that we have richer data coming from the SDK than we have on the Hub? As you're doing this, be thinking about how we could unify the two definitions and open or flag any relevant issues.

@tayloramurphy yeah this is also part of the reason why I like saving the raw --about output because down the line it might be better for the hub/meltano to accept settings as full on json schemas (I cant find the issue for that right now).

> Since the process is expensive, what about storing the output from --about into S3? We could do that right away, and then get to a second step for exactly how to apply it back to the repo. For failed executions or failed installations, you could instead save a record of the error text.

@aaronsteers I like that approach! I think I can get the extract process working pretty quickly but the translate/merge/update step will be a little trickier.
