### ISSUE TITLE
🐛 BUG: `Variant metrics are namespaced by repo and airbyte-wrapper shares repo` 

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1113]
The variant metrics are currently namespaced by repo name because up until now the repo was uniquely 1-1 with a tap. With tap-airbyte-wrapper many plugins share the same repo name so current state will likely lump all usage into one metric thats shared across all airbyte variants.

An example is https://github.com/meltano/hub/blob/78f076c0bf9b5177036ea509e33fcdf6bc31da2c/_data/variant_metrics.yml#L1143.

Potential Solution:
- It might be better to namespace metrics based on `{plugin_type}-{plugin_name}-{plugin_variant}` like we do in most other places.
- This would require an update to Squared pipelines that produce the data prior to working
- squared related link https://github.com/meltano/squared/issues/514

**Comment by tayloramurphy** [comment]
@pnadolny13 good catch on this!

**Comment by pnadolny13** [comment]
I think this was resolved naturally once we set the repo name to reference the subdirectory in the airbyte repo like `https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-adjust` and it flowed through Squared. I see plugin pages with different metrics:

- https://hub.meltano.com/extractors/tap-adjust--airbyte/ - 3/8
- https://hub.meltano.com/extractors/tap-jira--airbyte/ - 3/17
- https://hub.meltano.com/extractors/tap-s3--airbyte/ - 13/9
- https://hub.meltano.com/extractors/tap-amplitude--airbyte/ - 2/8
