### ISSUE TITLE
Make EDK preview utilities default

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1115]
We still have the EDK based dbt utilities as "Preview" https://hub.meltano.com/utilities/dbt-snowflake. I think we had enough time to sort out any bugs.

- remove preview label from dbt utilities
- hide transformer dbt versions and file bundle
- make Airflow EDK utility the default
- hide the Airflow orchestrator/files bundle
- make Superset EDK utility the default

**Comment by tayloramurphy** [comment]
@pnadolny13 there are a _ton_ of documentation updates that we will need to make to coincide with this change. This feels like a 3.0 level update since it'd such a change. @aaronsteers your thoughts?

**Comment by aaronsteers** [comment]
@tayloramurphy - I think there's a path forward where we deprecate the older dbt implementation without removing support. That would allow us to update docs recommending the new dbt implementations as the primary/default choice, without necessarily needing a major version bump.

Wdyt?

**Comment by pnadolny13** [comment]
@tayloramurphy yeah like AJ said, I was thinking that we could continue supporting as usual but update the hub to hide deprecated plugin types from searches and update the docs to recommend the utility syntax over orchestrators/transformers.

For docs I think a light lift for the first iteration would be to continue to refer to them as orchestrators/transformers and keep the docs the same except that example commands use `meltano add utility` instead of `meltano add transformer`. Even long term I dont hate calling them transformer utilities in docs even though theyre really all just plain utilities.
