### ISSUE TITLE
Improvement: Allow example values to be show on the hub

### ISSUE THREAD

**Issue by ZJvandeWeg** [meltano/hub#1116]
I just spend 30 minutes on getting the `target-bigquery` with a vague 404 error code. Appears the `location` field (default `us`) should've been the long form of the location.

**To Reproduce**
1. Install target-bigquery
2. Set location to US
3. Get a 404 code

**Expected behavior**
The config option on the hub could include an array with examples. That is, the file in this repo includes an examples array which gets rendered. This would include something like `europe-west1` etc and make clear to a user what value the config expects.

**Comment by pnadolny13** [comment]
@ZJvandeWeg thanks for raising this!

For what its worth, the [default in the target](https://github.com/adswerve/target-bigquery/blob/74ea806e1c681bd5d731b96e2ae8cc6f04c8ad9a/target_bigquery/__init__.py#L74) is actually `US` 🤔. If thats wrong or outdated (which it looks like it is) we can override it with a correct value in the [hub plugin definition](https://github.com/meltano/hub/blob/78f076c0bf9b5177036ea509e33fcdf6bc31da2c/_data/meltano/loaders/target-bigquery/adswerve.yml#L29). There's a few mechanisms for showing examples of input - [placeholder](https://docs.meltano.com/reference/plugin-definition-syntax#settingsplaceholder) attribute like in [target-snowflake for example](https://github.com/meltano/hub/blob/78f076c0bf9b5177036ea509e33fcdf6bc31da2c/_data/meltano/loaders/target-snowflake/transferwise.yml#L28) and by adding some extra info to the description field i.e. "for example `us-east1`".

Is this something you'd be interested in contributing?

**Comment by aaronsteers** [comment]
@tayloramurphy and @pnadolny13 - What do you think of reopening this so we can render 'placeholder' as 'example' values in the Hub details? 

The PR accomplished the 'needed' by _also_ setting the `value` default, but I think there will be cases where the example value would be helpful to render from 'placeholder' if it's available.

SDK-based taps can also use the JSON Schema 'examples' code to render one or more 'example' entries as 'placeholder'.

**Comment by tayloramurphy** [comment]
@aaronsteers I made a new issue for it https://github.com/meltano/hub/issues/1119 it'd be a pretty easy change.

**Comment by aaronsteers** [comment]
Great, thank you @tayloramurphy!
