### ISSUE TITLE
Replace Airbyte warning with compatibility warning and generic "low project usage" warnings

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#1143]
When anonymous telemetry reports less than 5 projects successfully running a tap or target over the rolling 90 day window, that is generally an indication that the tap is not working well, or has not been properly documented. We often get new users trying out these taps and getting frustrated if the first 3 or 4 taps they try out are difficult to setup or have some important documentation or usability bugs. 

## Why 5 minimum projects?

The first 2 or 3 projects are usually the developer themselves testing the plugin, so we should require at least 4 or 5 sightings "in the wild" and running successfully before we remove the top-of-page warning. Since the window is 90 days long, this should be plenty wide of a window to have a minimum usage volume established. (All of the tap-postgres variants have at least 30 projects  

## What should the warning say

The warning can emulate our current Airbyte "experimental" warning text (example [here](https://hub.meltano.com/extractors/tap-zenloop/#airbyte_config.survey_id-setting)), but does not need to be overly aggressive or "scary". The goal is not to prevent the user from downloading and testing the tap, but to steer new users to another implementation or another "first tap" to try when they are first getting started. This can also encourage maintainers and existing users of those taps to help improve docs and/or check for implementation bugs which may be affecting other users.

## Dropping "experimental" label from Airbyte

With this new warning above added based on "in the wild" implementations, we can remove the `tap-airbyte` experimental warning, and replace with some generic prereqs and compatibility notes that explain the inherent limitations of Airbyte-based taps, such as the need for docker-in-docker support, and related inability to run on ECS. We can link to Airbyte's own page explaining the limitation here: https://docs.airbyte.com/deploying-airbyte/on-aws-ecs/

We should also try to import or link to Airbyte's own maturity grade for the specific connector (optionally as a follow-on task), since many are clearly denoted as alpha or experimental, and we on the Hub should not skip over declaring those limitations and early-stage dev status warnings to our users.

Airbyte's warning to their users is:

> Alpha: An alpha connector signifies a connector under development and helps Airbyte gather early feedback and issues reported by early adopters. We strongly discourage using alpha releases for production use cases and do not offer Cloud Support SLAs around these products, features, or connectors.

And the link to their index with alpha/beta/GA evaluations is here: https://docs.airbyte.com/integrations/

If it is difficult to deep link or import this data to the Hub, we can at least provide the above link to allow potential users of wrapped Airbyte connectors to understand what level of maturity the connector is listed as.

**Comment by pnadolny13** [comment]
@aaronsteers I think this would be a great feature and starts to remind me of our gold/silver/broze discussions but I dont think this feature should be a blocker to removing the airbyte warning. I personally think we put a disproportionate weight on warning about Airbyte and I think the FAQ does a good job of calling out most of these things already.

I think sufficient info to remove the warning should be: a blurb at the top with a reference to the FAQ, mention that theres extra challenges with deploying container based plugins, and link to the alpha/beta/GA airbyte docs.

Would you be open to decoupling this feature from the Airbyte warning?

**Comment by pnadolny13** [comment]
I have more thoughts on the feature itself but I'm still ruminating a bit - I think 5 projects makes sense and I think framing it more like "we dont have enough data to be confident in this variant" vs "warning this is probably buggy" makes sense to me since theres only so much the data can reliably tell us. I'm starting to like a star feature where you get a star for each evaluation attribute:

- sufficient usage > 5 successful projects?
- SDK based
- maintenance status active in plugin definition and latest git commit within a year (when we know this)
- meltano/meltanolabs supported - maybe even generically org supported meaning meltano/transferwise/stitch/airbyte
- other stuff?

But that means meltanolabs tap-github https://hub.meltano.com/extractors/tap-github would be 4/4 stars high confidence in this case and airbyte tap-jira https://hub.meltano.com/extractors/tap-jira--airbyte/ would be 0/4 stars low confidence right now, which I dont think is a true reflection especially because Alex said airbyte's Jira tap was the reason he built the wrapper.

**Comment by aaronsteers** [comment]
Thanks, @pnadolny13 . Your feedback is much appreciated. I think we have a general park forward here. I'll defer on commenting on the stars/ranking until a bit later but the general direction is right, I think

> Would you be open to decoupling this feature from the Airbyte warning?

No, not really. We either need to warn about low usage, or Airbyte, or docker-in-docker/ECS limitations 

At least one of these warnings is required, I think.

**Comment by pnadolny13** [comment]
>No, not really. We either need to warn about low usage, or Airbyte, or docker-in-docker/ECS limitations

@aaronsteers I think we might be on the same page already 😄 - in [my comment](https://github.com/meltano/hub/issues/1143#issuecomment-1414126178) I was pitching:

>a blurb at the top with a reference to the FAQ, mention that theres extra challenges with deploying container based plugins, and link to the alpha/beta/GA airbyte docs.

At the top meaning the top of each airbyte plugin page. I'm just saying that I think we can add more details around challenges with Airbyte to remove the warning symbols/preview label without having to implement this "low usage" feature (which I think is a good idea but I'm suggesting we decouple the 2). Is that a reasonable path forward?

**Comment by aaronsteers** [comment]
Thanks for clarifying, @pnadolny13 . Maybe the minimum change is: "replace Airbyte warning with Docker-in-Docker warning" which is inferred from your comment above but I just would want to be really clear - especially to help prevent people from creating dev-time dependencies on components that are then not possible to deploy to their/our production environment.
