### ISSUE TITLE
ci: check plugin can be installed by its `pip_url` in PR checks

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/hub#1191]
From #1189:

> In the future, it would be nice to have a CI check here that attempts to pip install from the supplied `pip_url` to catch potential `meltano install` issues.

**Comment by aaronsteers** [comment]
Agreed. And thanks for logging.

Related:
- https://github.com/meltano/meltano/issues/7368

**Comment by ReubenFrankel** [comment]
Closing this since #1727 was merged a while back: https://github.com/meltano/hub/actions/workflows/test_meltano_add_install.yml
