### ISSUE TITLE
Add Partnerize Tap to Hub

### ISSUE THREAD

**Issue by omarabed15** [meltano/hub#1206]
An initial implementation of an extractor for the [Partnerize API](https://api-docs.partnerize.com/partner/) exists at https://github.com/voxmedia/tap-partnerize. This variant should be the default for the Partnerize extractor.

Currently, this extractor only implements the [Conversion Items](https://api-docs.partnerize.com/partner/#operation/Export%20Conversion%20Items) stream.

**Comment by tayloramurphy** [comment]
Closed in #1207
