### ISSUE TITLE
bug: netlify build is failing

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1247]
https://app.netlify.com/sites/meltano-hub/deploys/6435dbf9c078750008699c44

When it tries to run `aws s3 cp s3://<HUB_BUCKET>/prod/hub_metrics/variant_metrics.yml ./_data/variant_metrics.yml`

Its returning and error like:
`6:15:56 PM: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

cc @magreenbaum in case this is related to your recent infra changes

**Comment by magreenbaum** [comment]
Whoops, that looks to have been my fault. I did a refresh and apply on pulumi now and there was a missing policy attachment after I did some resource juggling earlier. Sorry about that @pnadolny13. It should be g2g now if that's rerunnable.

**Comment by pnadolny13** [comment]
@magreenbaum looks like it working now! Thanks for the quick fix

**Comment by tayloramurphy** [comment]
Guessing we can close this now?
