### ISSUE TITLE
bug: Metadata Refresh PR Job Failing

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1260]
I noticed that the metadata refresh workflow is failing due to permissions [as of today](https://github.com/meltano/hub/actions/runs/4725858271/jobs/8384880766). It doesnt look like anything in the code has changed since the [last passing run](https://github.com/meltano/hub/actions/runs/4669081226/jobs/8267039675).

<img width="925" alt="Screen Shot 2023-04-17 at 5 36 31 PM" src="https://user-images.githubusercontent.com/27376735/232616289-ed4edd1f-4948-445b-912c-5b77927cb2fd.png">

@magreenbaum @WillDaSilva any idea if anything related to permissions changed in this repo?

**Comment by WillDaSilva** [comment]
@pnadolny13 That's definitely my bad. I'll see if I can fix that.

**Comment by WillDaSilva** [comment]
@pnadolny13 Looks like it's fixed now: https://github.com/meltano/hub/actions/runs/4726107347/jobs/8385318803

Could you please confirm, and close the issue if so?

**Comment by pnadolny13** [comment]
@WillDaSilva yep looks like its resolved, thanks for the quick fix!
