### ISSUE TITLE
docs: minimum plugin standards to be listed on the hub

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#1307]
Related to https://github.com/meltano/hub/issues/1292 and https://github.com/meltano/hub/issues/1302

We should document the minimum criteria that we set for plugins to be listed on the hub. One that was proposed in https://github.com/meltano/hub/issues/1302 is that they all have a license.

Some initial thoughts are:

### All Plugins:
- install succeeds
- license in repo

### Maintenance Statuses - New SDK:
- beta:
  - TODOs from cookiecutter all completed
  - default SDK tests pass
  
- active:
  - activity in the last X days/weeks/months

Follow up questions:
- What do we do if they stop meeting the minimum standard after being listed already? Is there a grace period before removing?
- What do we do with all the existing plugins that were added before the standards were set? Should they get an exemption?

**Comment by tayloramurphy** [comment]
@pnadolny13 I'm actually ok with listing plugins that don't have a license, but we should just warn users about that fact and make an issue on the project.

**Comment by tayloramurphy** [comment]
From OH:

* Testing framework with SDK (Singer Spec at least)
* Publish to PyPI - pinning to specific release
* Static security analysis

**Comment by pnadolny13** [comment]
This was mostly completed by https://hub.meltano.com/tap-target-maintenance. We can spin off follow on issues if we need them.
