### ISSUE TITLE
Add extractor: tap-salesloft

### ISSUE THREAD

**Issue by MarkEstey** [meltano/hub#1466]
I've created a new tap for the Salesloft platform using the Meltano SDK and would appreciate help adding it to the Meltano Hub!

Repository: https://github.com/MarkEstey/firehose-tap-salesloft

**Comment by tayloramurphy** [comment]
@MarkEstey awesome! https://github.com/meltano/hub/pull/1460/files is an example of a PR and all of the files we'd need. @pnadolny13 can help with this too 😄
