### ISSUE TITLE
feat: Improve settings UX

### ISSUE THREAD

**Issue by ReubenFrankel** [meltano/hub#1545]
As a user of a plugin, I would like to be able to see the config required to get the tap working at a minimum first, before optional settings defined by the developer or inherited from the SDK.

---

For example, [`tap-shopify`](https://hub.meltano.com/extractors/tap-shopify/) was [initially added to the hub](https://github.com/meltano/hub/blob/be46311be9186f116ba84c71ba9c1029e47cdf2b/_data/meltano/extractors/tap-shopify/matatika.yml) with the following developer-defined settings:

- `access_token`
- `store`
- `admin_url`
- `start_date`
- `is_plus_account`

[Now](https://github.com/meltano/hub/blob/bfc7c70f8d68f466b02f3c3f72e45fd9be9148ca/_data/meltano/extractors/tap-shopify/matatika.yml), implicit SDK settings are merged with developer-defined settings:

- `access_token`
- `admin_url`
- `batch_config.encoding.compression`
- `batch_config.encoding.format`
- `batch_config.storage.prefix`
- `batch_config.storage.root`
- `flattening_enabled`
- `flattening_max_depth`
- `is_plus_account`
- `start_date`
- `store`
- `stream_map_config`
- `stream_maps`

The problem here is that `store`, for example, is a (conditionally) required setting and, due to alphabetical sorting, is hidden amongst settings that are not required and/or not defined by the developer originally. This makes it hard to see what a user needs to provide to get the tap working at a minimum.

The quickest fix here might be to stop sorting settings alphabetically in the plugin definition `.yml` files and display them in the order that they are defined, in an effort to group by importance and behaviour. It would also be good to group optional settings by whether they were explicitly defined by the developer or inherited from the SDK (given the plugin was built with the SDK) - maybe there could be an `Advanced` or `SDK-inherited` subsection? In the long-term, perhaps there needs to be a better implementation of `settings_group_validation`, in order to show the required (unconditionally and conditionally) settings first, followed by the unconditionally optional settings.

**Comment by tayloramurphy** [comment]
@ReubenFrankel great idea. Is there any metadata on the settings coming from the SDK? We could likely add something to the SDK and key off that on the Hub.

**Comment by ReubenFrankel** [comment]
@tayloramurphy I don't know anything about setting metadata from the SDK (unclear if that question was directed at me). I was thinking that you could infer these settings from `capabilities`, if the plugin was build with the SDK.

**Comment by tayloramurphy** [comment]
@ReubenFrankel that would make sense to me. I don't know off the top of my head if all SDK settings have an equivalent capability. @edgarrmondragon do you know?

**Comment by edgarrmondragon** [comment]
> @ReubenFrankel that would make sense to me. I don't know off the top of my head if all SDK settings have an equivalent capability. @edgarrmondragon do you know?

Depends on the version of the SDK that they install. They may report a capability, but the setting may not be added to the config schema. The tap/target _could_ still be able to use the setting, but it'd have no validation.

Definitely the safest is to use the actual output of `--about`, but that requires changes to the SDK to communicate it's a built-in setting, and that plugins adopt the latest version.
