### ISSUE TITLE
Teradata Target

### ISSUE THREAD

**Issue by Crudelis-rgb** [meltano/hub#1604]
### What is the plugin type?

loader

### Repository URL

https://github.com/Crudelis-rgb/target-teradata

### Description

Teradata is multi-cloud data platform for enterprise analytics

### Domain URL

https://docs.teradata.com/

### Logo Image

![teradata logo](https://github.com/meltano/hub/assets/53942137/a3f7646e-acc2-4d5a-8f94-474aaebb6d96)

### Any other notes?

This is my first open-source contribution. So please be nice :)

**Comment by pnadolny13** [comment]
@Crudelis-rgb this is fantastic! Thanks for contributing.

It's live at https://hub.meltano.com/loaders/target-teradata
