### ISSUE TITLE
Add Plugin: <insert plugin name>

### ISSUE THREAD

**Issue by dineshssdn-867** [meltano/hub#1635]
### What is the plugin type?

extractor

### Repository URL

https://github.com/singer-io/tap-ms-dynamics

### Description

This is the tap for dataverse

### Domain URL

https://github.com/singer-io/tap-ms-dynamics

**Comment by pnadolny13** [comment]
@dineshssdn-867 I can get this added! I'm less familiar with the MS suite of products though so I'm not sure where to list it. Is this the same system as these other taps https://hub.meltano.com/extractors/tap-dynamics? Or should it be a standalone plugin page?

**Comment by dineshssdn-867** [comment]
Actually, I was testing tap-dynamics, but it is not a stable version, and I am getting errors. So, I found this new version which is stable. Also, can you help me how to use this in my meltano project ?

**Comment by dineshssdn-867** [comment]
It should be a standalone plug-in.

**Comment by pnadolny13** [comment]
Ok feel free to link the stable version too if its not listed on the hub yet. I added this variant so its discoverable for other user (even if its out of date). I assumed it was best to put it under the existing dynamics plugin page.

>Also, can you help me how to use this in my meltano project ?
I'd suggest joining the slack community if you have questions! https://meltano.com/slack

**Comment by dineshssdn-867** [comment]
Sure, thanks for the help and thanks for raising the PR.
