### ISSUE TITLE
Add Plugin: tap-fleetio

### ISSUE THREAD

**Issue by jmmizerany** [meltano/hub#1685]
### What is the plugin type?

extractor

### Repository URL

https://github.com/fleetio/tap-fleetio

### Description

Fleet Maintenance Management Software

### Domain URL

https://developer.fleetio.com

### Logo Image

![fleetio-logo-mark-only](https://github.com/meltano/hub/assets/97474773/8a2b5fc7-8f84-42e0-803c-3c46909e6f4a)

**Comment by edgarrmondragon** [comment]
Hey @jmmizerany! See https://github.com/meltano/hub/pull/1686
