### ISSUE TITLE
Add Plugin: tap-kiotviet

### ISSUE THREAD

**Issue by chienazazaz** [meltano/hub#1695]
### Repository URL

https://github.com/chienazazaz/tap-kiotviet

### Description

KiotViet is among one of the largest POS provider in Vietnam. This tap is for Vietnamese folks

### Domain URL

https://www.kiotviet.vn/

**Comment by edgarrmondragon** [comment]
Hey @chienazazaz, thanks for filing!

The domain URL usually points to the homepage of the source in question rather than the repo URL.

Is [kiotviet.vn](https://www.kiotviet.vn/) the right domain for this source?

**Comment by chienazazaz** [comment]
> Hey @chienazazaz, thanks for filing!
> 
> The domain URL usually points to the homepage of the source in question rather than the repo URL.
> 
> Is [kiotviet.vn](https://www.kiotviet.vn/) the right domain for this source?

yup, my bad =))))))
