### ISSUE TITLE
Add Plugin: tap-airtable

### ISSUE THREAD

**Issue by tomasvotava** [meltano/hub#1765]
### What is the plugin type?

extractor

### Repository URL

https://github.com/tomasvotava/tap-airtable

### Description

Airtable is the fastest way to build apps with zero code.

### Domain URL

https://airtable.com/developers/web/api/introduction

### Logo Image

![airtable](https://github.com/meltano/hub/assets/39478939/08a65505-6bf6-4700-ba80-515aebd9b49c)

### Any other notes?

I wasn't able to run any of the existing Airtable taps available (the default version was not runnable and the Airbyte version requires docker which can be bad for some Meltano deployments).

**Comment by edgarrmondragon** [comment]
@tomasvotava thanks for sharing! See https://github.com/meltano/hub/pull/1770.
