### ISSUE TITLE
Add Plugin: target-db2

### ISSUE THREAD

**Issue by haleemur-infostrux** [meltano/hub#1807]
### What is the plugin type?

loader

### Repository URL

https://github.com/Infostrux-Solutions/target-db2

### Description

Singer Target for IBM Db2, built with singer-sdk by Meltano

### Domain URL

https://github.com/Infostrux-Solutions/target-db2

### Logo Image

<img src="https://github.com/user-attachments/assets/e6b5330f-cbf2-43b2-8be3-94ea785eccc1" alt="Db2">

### Any other notes?

singer target plugin that is able to load data into ibm.com/db2

**Comment by edgarrmondragon** [comment]
The missing arm64 wheels for macos are giving me problems to determine the settings automatically, and I'd rather not risk missing something 😅.

So, PRs welcome :)

**Comment by haleemur-infostrux** [comment]
@edgarrmondragon I'm happy to spend some time resolving this issue. do you have any guidance on how I can build arm64 wheels or an example PR which I can follow.

Also, `target-db2` should be pip installable.
