### ISSUE TITLE
Clarify LICENSE

### ISSUE THREAD

**Issue by pbower** [meltano/hub#1906]
Hi, 

There is no LICENSE file in this repository. Could you please confirm if the LICENSE from the Meltano repository applies here?

Thanks,
Pete

**Comment by edgarrmondragon** [comment]
Hi @pbower, thanks for opening the issue.

I'm not very familiar with legal. Can you expand on why you need clarification about the license of this repo?

**Comment by edgarrmondragon** [comment]
@ReubenFrankel I think y'all use either a fork or a compatible implementation, what do you think of adding an Apache-2 License to this repo?

**Comment by edgarrmondragon** [comment]
https://github.com/meltano/hub/pull/1910
