### ISSUE TITLE
Potential design update for Classic MeltanoHub

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#519]
Per discussion in Leadership call, it would be good to at least have a minimal update prepped for the launch. 

TBD on possible design

cc @DouweM @aaronsteers

**Comment by DouweM** [comment]
All the research I've done on this so far is opening these tabs, showing index and detail pages on 4 package manager registries that can serve examples:

- https://hub.docker.com/search?q=
- https://hub.docker.com/r/meltano/meltano
- https://www.npmjs.com/
- https://www.npmjs.com/package/vue
- https://rubygems.org/
- https://rubygems.org/gems/gitlab
- https://pypi.org/
- https://pypi.org/project/meltano/

**Comment by DouweM** [comment]
@tayloramurphy I've unassigned myself, but you may still want to prioritize this. Unless it makes more sense to go straight for the full redesign

**Comment by aaronsteers** [comment]
@DouweM / @tayloramurphy - Can we close this? I don't see a spec we could implement and I'd rather focus on the long-term redesign.

**Comment by tayloramurphy** [comment]
I close as not planned but if someone wants to do a slight redesign for hack day I'm not going to stop them!
