### ISSUE TITLE
Hub not rending tip and warning sections in markdown 

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#549]
https://hub.meltano.com/extractors/stripe is an example

FYI @DouweM if you know a quick fix when you're working on the Hub

**Comment by DouweM** [comment]
@tayloramurphy Did these use to work here, or only pre-Jekyll? tip/warning sections are not an official Markdown feature so it's possible the Markdown rendered we use here never supported it.

**Comment by tayloramurphy** [comment]
@DouweM AFAIK it never supported it oh the Hub. It was supported when the markdown files lived in the Meltano docs though.
