### ISSUE TITLE
Update Singer API to be generated from the single YAML file

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#562]
Looking at what we have on the Meltano API for a tap like `Auth0`:

<details>
<summary>Meltano tap-Auth0 json</summary>
<code>
{
    "description": "Authentication and Authorization Platform",
    "label": "Auth0",
    "name": "tap-auth0",
    "logo_url": "https://hub.meltano.com/assets/logos/taps/auth0.png",
    "namespace": "tap_auth0",
    "variant": "matatika",
    "pip_url": "git+https://github.com/Matatika/tap-auth0.git",
    "repo": "https://github.com/Matatika/tap-auth0",
    "settings_group_validation":
    [
        [
            "client_id",
            "client_secret",
            "domain"
        ]
    ],
    "settings":
    [
        {
            "name": "client_id",
            "label": "Client ID",
            "kind": "password",
            "description": "App client ID"
        },
        {
            "name": "client_secret",
            "label": "Client secret",
            "kind": "password",
            "description": "App client secret"
        },
        {
            "name": "domain",
            "label": "Domain",
            "description": "Tenant domain"
        },
        {
            "name": "job_poll_interval_ms",
            "label": "Job poll interval",
            "value": 2000,
            "kind": "integer",
            "description": "Job poll interval (ms)"
        },
        {
            "name": "job_poll_max_count",
            "label": "Maximum job poll count",
            "value": 10,
            "kind": "integer",
            "description": "Maximum job poll count"
        }
    ],
    "capabilities":
    [
        "catalog",
        "discover",
        "state",
        "about",
        "stream-maps"
    ]
}
</code>
</details>

vs what we have in #537 for `Auth0`

<details>
<summary>Singer tap-Auth0 json</summary>
<code>
{
    "description": "Authentication and Authorization Platform",
    "label": "Auth0",
    "name": "auth0",
    "singer_name": "tap-auth0",
    "type": "tap",
    "variants":
    [
        {
            "name": "nickhould",
            "maintenance_status": "unknown",
            "default": false,
            "pip_url": "git+https://github.com/nickhould/tap-auth0.git",
            "repo": "https://github.com/nickhould/tap-auth0",
            "settings":
            [],
            "capabilities":
            [
                "catalog",
                "discover"
            ],
            "maintainer":
            {
                "label": "Jean-Nicholas Hould",
                "url": "https://github.com/nickhould",
                "plugins":
                [
                    {
                        "url": "/taps/auth0--nickhould",
                        "logo_url": "/assets/logos/taps/auth0.png",
                        "label": "Auth0"
                    }
                ],
                "page_url": "/singer/maintainers/nickhould"
            },
            "metrics":
            {
                "CREATED_AT_TIMESTAMP": "2020-04-07 02:42:45 +0000",
                "NUM_OPEN_ISSUES": 0,
                "NUM_FORKS": 3,
                "LAST_PUSH_TIMESTAMP": "2020-04-07 03:25:32 +0000",
                "LAST_UPDATED_TIMESTAMP": "2020-04-07 03:25:34 +0000",
                "NUM_STARGAZERS": 0,
                "MELTANO_PROJECT_ID_COUNT_3M": 2,
                "NUM_WATCHERS": 0,
                "MELTANO_EXEC_COUNT_3M": 22
            },
            "url": "/taps/auth0--nickhould"
        },
        {
            "name": "matatika",
            "default": true,
            "meltano_sdk": true,
            "maintenance_status": "active",
            "pip_url": "git+https://github.com/Matatika/tap-auth0.git",
            "repo": "https://github.com/Matatika/tap-auth0",
            "settings_group_validation":
            [
                [
                    "client_id",
                    "client_secret",
                    "domain"
                ]
            ],
            "settings":
            [
                {
                    "name": "client_id",
                    "label": "Client ID",
                    "kind": "password",
                    "description": "App client ID"
                },
                {
                    "name": "client_secret",
                    "label": "Client secret",
                    "kind": "password",
                    "description": "App client secret"
                },
                {
                    "name": "domain",
                    "label": "Domain",
                    "description": "Tenant domain"
                },
                {
                    "name": "job_poll_interval_ms",
                    "label": "Job poll interval",
                    "value": 2000,
                    "kind": "integer",
                    "description": "Job poll interval (ms)"
                },
                {
                    "name": "job_poll_max_count",
                    "label": "Maximum job poll count",
                    "value": 10,
                    "kind": "integer",
                    "description": "Maximum job poll count"
                }
            ],
            "capabilities":
            [
                "catalog",
                "discover",
                "state",
                "about",
                "stream-maps"
            ],
            "maintainer":
            {
                "label": "Matatika",
                "url": "https://www.matatika.com/",
                "plugins":
                [
                    {
                        "url": "/taps/auth0--matatika",
                        "logo_url": "/assets/logos/taps/auth0.png",
                        "label": "Auth0"
                    },
                    {
                        "url": "/taps/googleads--matatika",
                        "logo_url": "/assets/logos/taps/googleads.png",
                        "label": "Google Ads"
                    },
                    {
                        "url": "/taps/google-sheets--matatika",
                        "logo_url": "/assets/logos/taps/google-sheets.png",
                        "label": "Google Sheets"
                    },
                    {
                        "url": "/taps/meltano--matatika",
                        "logo_url": "/assets/logos/taps/meltano.png",
                        "label": "Meltano"
                    },
                    {
                        "url": "/taps/openweathermap--matatika",
                        "logo_url": "/assets/logos/taps/openweathermap.png",
                        "label": "OpenWeatherMap"
                    },
                    {
                        "url": "/taps/shopify--matatika",
                        "logo_url": "/assets/logos/taps/shopify.png",
                        "label": "Shopify"
                    },
                    {
                        "url": "/taps/solarvista--matatika",
                        "logo_url": "/assets/logos/taps/solarvista.png",
                        "label": "Solarvista Live"
                    },
                    {
                        "url": "/taps/spotify--matatika",
                        "logo_url": "/assets/logos/taps/spotify.png",
                        "label": "Spotify"
                    },
                    {
                        "url": "/taps/thunderboard--matatika",
                        "logo_url": "/assets/logos/taps/thunderboard.png",
                        "label": "Thunderboard"
                    },
                    {
                        "url": "/taps/trello--matatika",
                        "logo_url": "/assets/logos/taps/trello.png",
                        "label": "Trello"
                    }
                ],
                "page_url": "/singer/maintainers/matatika"
            },
            "metrics": null,
            "url": "/taps/auth0--matatika"
        },
        {
            "name": "process-street",
            "maintenance_status": "unknown",
            "pip_url": "git+https://github.com/process-street/tap-auth0-logs-checkpoint.git",
            "repo": "https://github.com/process-street/tap-auth0-logs-checkpoint",
            "settings":
            [],
            "capabilities":
            [
                "catalog",
                "discover"
            ],
            "maintainer":
            {
                "label": "Process Street",
                "url": "https://www.process.st/",
                "plugins":
                [
                    {
                        "url": "/taps/auth0--process-street",
                        "logo_url": "/assets/logos/taps/auth0.png",
                        "label": "Auth0"
                    },
                    {
                        "url": "/taps/process-street--process-street",
                        "logo_url": "/assets/logos/taps/process-street.png",
                        "label": "Process Street"
                    }
                ],
                "page_url": "/singer/maintainers/process-street"
            },
            "metrics":
            {
                "CREATED_AT_TIMESTAMP": "2020-11-14 10:58:31 +0000",
                "NUM_OPEN_ISSUES": 0,
                "NUM_FORKS": 0,
                "LAST_PUSH_TIMESTAMP": "2020-11-18 10:55:37 +0000",
                "LAST_UPDATED_TIMESTAMP": "2020-11-18 10:55:39 +0000",
                "NUM_STARGAZERS": 0,
                "MELTANO_PROJECT_ID_COUNT_3M": 0,
                "NUM_WATCHERS": 0,
                "MELTANO_EXEC_COUNT_3M": 0
            },
            "url": "/taps/auth0--process-street"
        }
    ],
    "entity_url": "https://auth0.com/",
    "entity_type": "api",
    "logo_url": "/assets/logos/taps/auth0.png",
    "url": "/taps/auth0"
}
</code>
</details>

We should still be able to generate it and keep the v1 endpoint up to date. 

cc @pnadolny13 @DouweM

**Comment by pnadolny13** [comment]
@tayloramurphy yep we can do this but its is a little tricky because the schemas changed. I think the main thing is collapsing all variants under a list if there are many or at the top level if theres just one. A few other changes I can think of (not a complete list) are:
- default and singer_name attributes were removed
- `keywords` now contain `entity_type` and `meltano_sdk` combined into a list, so they need to get split out back to their own stand alone attributes

**Comment by tayloramurphy** [comment]
Closing as we are deprecating the dedicated Singer API.
