### ISSUE TITLE
Update "Add New Singer Connector" issue template for GitHub

### ISSUE THREAD

**Issue by DouweM** [meltano/hub#566]
https://github.com/meltano/hub/blob/main/.gitlab/issue_templates/Add%20New%20Singer%20Connector.md is in the `.gitlab` directory, and talks about GitLab features like Merge Requests and the Web IDE. We should update it!

@tayloramurphy For you to schedule

**Comment by edgarrmondragon** [comment]
An [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) might be cool for this 😄 

Also, that template would be nice to link from https://docs.meltano.com/contribute/plugins#discoverable-plugins

**Comment by DouweM** [comment]
@edgarrmondragon Good point! I think the https://docs.meltano.com/contribute/plugins docs are the main document here, and the issue template/form supports them. Created some related issues: https://github.com/meltano/meltano/issues/6107, https://github.com/meltano/meltano/issues/6106

**Comment by aaronsteers** [comment]
Thanks for opening this! I think we should _separately_ have a similar link for utility plugins, but probably two forms (or perhaps more!) is best here so the prompts are on-topic.

I think actually three might be nice, but we can also keep the first two combined:

- New tap
- New target
- New tool or utility (other)

**Comment by edgarrmondragon** [comment]
Addressed by #587!
