### ISSUE TITLE
Fetch metrics from S3 when deploying Hub

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#567]
Switching to Netlify broke what we had on Pages

https://gitlab.com/meltano/legacy-ci/hub/-/blob/main/.gitlab-ci.yml#L38-39

**Comment by aaronsteers** [comment]
Sounds like we need to:

1. [ ] Add S3 creds to the netlify config: https://app.netlify.com/sites/meltano-hub/settings/deploys#environment
2. [ ] Find where Netflify gets its build instructions and try to inject these two lines: https://gitlab.com/meltano/legacy-ci/hub/-/blob/main/.gitlab-ci.yml#L38-39

Does that approach sound reasonable? @pandemicsyn, @tayloramurphy, @pnadolny13 , @alexmarple, @afolson

**Comment by tayloramurphy** [comment]
Part of the CI script was getting the aws cli installed as well, so as long as there are no limitiations on curl and zip that should be ok

**Comment by aaronsteers** [comment]
TIL: `netlify.toml`: https://docs.netlify.com/configure-builds/file-based-configuration/

**Comment by aaronsteers** [comment]
We considered above using AWS CLI commands as were previously part of the CI build.

However, I think we probably should just move this to the Gridsome page build process natively. Also, spoke with @tayloramurphy and we agreed we'll skip the Jekyll side to prioritize the new Gridsome site.

**Comment by tayloramurphy** [comment]
@aaronsteers as part of this issue can the Hub be setup to deploy data so there's minimal delay on the metrics?

**Comment by rwfeather** [comment]
Getting the netlify build process to run the same AWS cli flow is feeling kinda tricky (currently experimenting with adding the steps to a makefile, changing netlify build command to `make bundle`)

@aaronsteers @alexmarple: If I understand correctly, the gridsome approach would be something like the [data imports](https://gridsome.org/docs/fetching-data/#yaml), correct? That seems like a viable approach to me, especially if we'll be fine not fixing this for the existing site.

I also just have a question that might simplify build-time concerns: Are the `metrics.yml` and `audit.yml` files sensitive at all? If they aren't, we could open up their permissions slightly in s3 and access them publicly at their URL (https://prod-meltano-bucket-01.s3.us-east-2.amazonaws.com/hub_metrics/audit.yml). That would let us do a simple curl or `fetch()` as part of the gridsome data import.
