### ISSUE TITLE
Rebuilt plugin-specific usage metrics

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#570]
The prior usage metrics for plugins were not able to distinguish the actual variant being used, and therefor had incorrect (inflated) usage metrics. For instance, all `tap-postgres` implementations would have usage metrics of the full combined usage across each.

We'll want to rebuild these metrics now with variant-specific metrics, now that we will have access to this distinction.

**Comment by pnadolny13** [comment]
This issue depends on https://github.com/meltano/squared/issues/275 in order to unhash variant names. 

Also I opened https://github.com/meltano/hub/issues/639 to get the current metrics updated to make it more clear that theyre not variant level.

**Comment by tayloramurphy** [comment]
Thanks for opening the issue @pnadolny13. Moving this out a few iterations in that case.

**Comment by pnadolny13** [comment]
Theres more detail on how we want to expose these numbers related to Success/Failure attribution in https://github.com/meltano/squared/issues/298#issuecomment-1187708092. I closed that one because it was a duplicate.

**Comment by pnadolny13** [comment]
@aaronsteers @tayloramurphy I unassigned myself from this as I'm working on making the data available in https://github.com/meltano/squared/issues/298#issuecomment-1187708092.

Once its available, I believe @alexmarple or @rwfeather would be the one actually taking on this work to update how the hub uses it.
