### ISSUE TITLE
docs: Document more clearly how to override settings/capabilities locally

### ISSUE THREAD

**Issue by DouweM** [meltano/hub#580]
https://hub.meltano.com/extractors/tap-aconex#capabilities suggests updating the YAML file, but that doesn't help the user get it working locally. We now support overriding `capabilities`/`settings` in `meltano.yml`, and should document this.

Related to https://github.com/meltano/hub/issues/527 and https://github.com/meltano/meltano/issues/6029.

**Comment by DouweM** [comment]
@tayloramurphy Can you please prioritize this? I feel like we also had a follow-up issue already about updating these docs.

**Comment by tayloramurphy** [comment]
I'd like the scope of this issue to be:

* Adding some text in https://hub.meltano.com/extractors/tap-abcfinancial#capabilities indicating as much with a link to _new_ documentation

I'm going to make a new issue in the Meltano project for the new documentation bit and cross-link.

**Comment by aaronsteers** [comment]
Might be related, new plugin params reference doc:

- https://docs.meltano.com/reference/plugin-definition-syntax
