### ISSUE TITLE
feat: list Mappers as available plugins 

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#589]
We should add mappings to the Hub. I think this can be after the redesign. I'd like them to be tied to Extractors somehow so it's clear they're not standalone.

**Comment by sbalnojan** [comment]
@tayloramurphy Decouple? Sounds like a discussion blocked mappers from being on the hub side for 4 months. Since this is a really powerful feature, why don't we add them somewhere (hello utility :-D) and then reschuffle them later on.
