### ISSUE TITLE
Broken link(s) to variant alternates

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#605]
When following the `singer-io` link here: https://hub.meltano.com/extractors/tap-salesforce

<img width="739" alt="image" src="https://user-images.githubusercontent.com/18150651/173921849-c4cefa4e-e851-4766-a009-9991a4b43072.png">

Injecting a `tap-` to the URL fixes this:

https://hub.meltano.com/extractors/tap-salesforce--singer-io

**Comment by aaronsteers** [comment]
@tayloramurphy - Do you and @pnadolny13 want to pick this up?

I'm happy to assign to an engineer otherwise.

I think (?) this probably is in the detail-page liquid template, and should be a quick fix.

**Comment by tayloramurphy** [comment]
@aaronsteers I already opened https://github.com/meltano/hub/pull/606 to get this sorted.
