### ISSUE TITLE
tap-google-analytics default `key_file_location` setting overrides user's `client_secrets` setting

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#611]
Related to https://github.com/MeltanoLabs/tap-google-analytics/issues/36

The tap accepts credentials via `key_file_location` with a path to a json file containing the credentials or with `client_secrets` that is a dict containing the credentials. The Meltano [definition defaults `key_file_location`](https://github.com/meltano/hub/blob/c8907cd69de11e87a0d7ca6f70d7c579110ad7b8/_data/meltano/extractors/tap-google-analytics/meltanolabs.yml#L31) so when a user wants to use `client_secrets` its not being picked up because the default setting is taking precedence.

@Atif8Ted who raised the issue in the tap repo was able to work around this by setting the `key_file_location` to an empty string but thats not ideal. I'd propose to delete the default value but I'm not sure of the implications of that. I'm hoping the lock file mechanism would help us not break existing pipelines but im not positive.

This was a setting brought over from discovery.yml  - cc @edgarrmondragon @tayloramurphy @aaronsteers

**Comment by tayloramurphy** [comment]
@pnadolny13 I'm surprised it's not respecting the settings_group_validation. @edgarrmondragon do we not do anything with that on the Meltano side?

**Comment by edgarrmondragon** [comment]
@tayloramurphy yes, but the problem is both values are set and the tap prioritizes `key_file_location`: https://github.com/MeltanoLabs/tap-google-analytics/blob/307f483782446fb9248367c8ec5ced93854778b5/tap_google_analytics/tap.py#L99-L106.

That's why setting it to an empty string forces it to use `client_secrets`.

**Comment by tayloramurphy** [comment]
@edgarrmondragon hrm. 

Well in that case I think we'd be okay to remove the value and put in for the placeholder and/or add it as a recommend option to the instructions:

```yaml
  placeholder: Ex. $MELTANO_PROJECT_ROOT/client_secrets.json
```
