### ISSUE TITLE
Add the dbt build command to the dbt transformer plugin

### ISSUE THREAD

**Issue by JulesHuisman** [meltano/hub#621]
Currently all dbt commands are there, however the command responding to `dbt build` is missing. 

Should this be added [here](https://github.com/meltano/meltano/blob/4deafc883a9b0ffbf2fc87e4a4be28cb20034ce4/src/meltano/core/bundle/discovery.yml#L2985)? If that is the case, I can create a pull request!

**Comment by tayloramurphy** [comment]
@JulesHuisman would love a PR for this and any other commands you think are useful to the wider community!

**Comment by edgarrmondragon** [comment]
@JulesHuisman you might wanna make that update in https://github.com/meltano/hub/tree/main/_data/meltano/transformers 😄

**Comment by aaronsteers** [comment]
@JulesHuisman - As @edgarrmondragon points out, `discovery.yml` actually deprecated/frozen at this time. The directory @edgarrmondragon  points you at is where this would live in the post-2.0 world. 

Thanks!

**Comment by tayloramurphy** [comment]
@edgarrmondragon @aaronsteers the PR in https://github.com/meltano/hub/pull/623 is doing the right thing 😄 I transferred this to the Hub repo previously 👍
