### ISSUE TITLE
Re-label metrics to make it clear that theyre not variant level

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#639]
The metrics shown on the plugin page includes all variants combined. Its documented in https://hub.meltano.com/singer/docs#meltano-usage-metrics but its a little mis leading on the plugin page.

Since we have another iteration to add variant level metrics, it would be good to relabel the current metrics for now. Maybe 
"Executions (Last 3 Months)" -> "All Variant Executions (Last 3 Months)" or renaming the "Meltano Stats" header to reflect that its all variants. Later we can add variant specific metrics and probably remove the old non-variant specific metrics.

cc @rwfeather @tayloramurphy @alexmarple

**Comment by tayloramurphy** [comment]
@pnadolny13 it'd be quickest for you to make this change but I want to make sure @rwfeather and @alexmarple are aware of it as well. Do you all want to do a pair session on this or what makes the most sense from y'alls perspective? cc @aaronsteers
