### ISSUE TITLE
Rebuild MeltanoHub daily to get fresh metrics

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#640]
Now that we're pulling metrics into the Hub via Netlify when building, we should rebuild this on a daily basis to get up to date metrics with the work done in the Squared project. 

@rwfeather suggested doing something with GitHub Actions if there isn't a way to natively rebuild the site on a daily basis in Netlify.

**Comment by aaronsteers** [comment]
@rwfeather - Looks good. 👍 We've put into the current iteration so feel free to pick up when ready. Also, if you can add a estimated weight, would be much appreciated. Thanks!
