### ISSUE TITLE
Revamp: Setup redirects for subfolder plugin names to default variant

### ISSUE THREAD

**Issue by alexmarple** [meltano/hub#655]

**Comment by tayloramurphy** [comment]
@alexmarple is this issue about the URLs? Something like https://meltano-hub-gridsome.netlify.app/extractors/tap-insided/karbonhq/ should keep the same behavior as the existing Hub so that the URL is still https://meltano-hub-gridsome.netlify.app/extractors/tap-insided/

**Comment by rwfeather** [comment]
@tayloramurphy yup, the intention here it to recreate the existing hub behavior. I've been looking into it for a bit this morning so I'll just go ahead and pick up this issue
