### ISSUE TITLE
Move all logo images to `src/assets/ui/logos` (no subfolders) and add explicit relative refs

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#676]
I'm noting this as a Revamp issue, but it might actually be easier to implement on `main` first and then import into `gridsome-main`.

Rather than have logos live at

- `src/assets/ui/logos/<plugin-type>/logoname.png`

We can simplify this to:

- `src/assets/ui/logos/logoname.png`

If we end up with specialized logos for different plugin types, such as a different `dbt-snowflake` logo than the `tap-snowflake` logo, those can simply be named accordingly but still reside within the same folder.

As a prerequisite for this change:

1. We may need to double check if the `logo_url` property is working correctly during page generation (with relative or absolute refs) so that logos are able to be properly reused and/or redirected as appropriate.
2. We may want to do a one-time update all of the plugin yaml files with an explicit relative reference to the appropriate logo. Currently, these are 'magic' in that they find the right logo based on naming convention instead of through an explicit ref.

Related:

- Logos represent a few hundred files in the currently WIP PR: #663 

Alternatives:

1. We could decide to leave as-is, with logos found through convention based on plugin type.
1. We could move logos into the data directory as siblings of the yaml definitions.
   - This has the advantage of "everything in one place" and still meets "explicit is better than implicit".
   - The disadvantage would be redundancies of storing the same logos potentially multiple times and not very DRY when it comes to a brand's logo getting updated.

@rwfeather and @alexmarple - Any thoughts on this? Preferences or suggestions?

**Comment by alexmarple** [comment]
@aaronsteers 

Yeah I agree that we no longer need a plugin type subfolder for the org icons.

Probably for the best to do it in `main`. I can tackle these items in a couple of days from now.

**Comment by alexmarple** [comment]
@aaronsteers since this will be done in the clean up of files when we jettison the jekyll stuff this can probably be closed yeah?

**Comment by aaronsteers** [comment]
@alexmarple - Do you mean as part of #731 ?

I'm fine if it gets delivered as part of #731 but since the PR is not really usable in its current state (page loading and large number of files changed), I think we need to keep this open until those are removed, and I think we should priortize #731 and also moving the directory to the project root to get done asap so we can be working from a clean tree.

**Comment by aaronsteers** [comment]
@rwfeather - Do you mind picking this up as high pri? Ideally it would be nice to have this done before the review meeting, but that timeline may be too aggressive at this point. Lmk.

**Comment by rwfeather** [comment]
@aaronsteers I tried to accomplish this in the same PR as #657, but I ran into some issues getting things to work. Getting webpack/gridsome to load images from from the top level assets was not as simple as I expected. Worked well for our data files, but we were loading those in by hand rather than messing with webpack configuration. Ended up holding off on it to get the images working ASAP.

I'm looking into it at the moment with some fresh eyes, but if I can't find a solution we might have to wait until we move everything into the top-level directory. Things will just work when we reach that point.

**Comment by aaronsteers** [comment]
@rwfeather - Thanks. The challenge of accessing files from a higher-level than root makes sense. Agreed; no point in finding workarounds which we won't need when the base directory is bumped up to root.

Probably means we need to bump up priority on 

- #739 

I'll mark that one as `Urgency: High` to reflect this.

**Comment by rwfeather** [comment]
Resolved by #747
