### ISSUE TITLE
bug: "Edit it on GitHub" links are broken

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#682]
https://github.com/meltano/hub/blob/main/_data/meltano/transformers/dbt-bigquery/dbt-labs.yml from https://hub.meltano.com/transformers/dbt-bigquery#looking-for-help does not load for me. If I switch `blob` to `tree` it does.

**Comment by DouweM** [comment]
@tayloramurphy Same here, and Dev Tools show a 406 status code:

<img width="682" alt="Screen Shot 2022-07-25 at 10 03 48" src="https://user-images.githubusercontent.com/159434/180810074-2668a3c9-7dba-4705-8a2e-370c518b92f0.png">
 
I don't know if this is related, but DevTools also show that the `href` attribute has whitespace around the URL, which probably doesn't help.

**Comment by edgarrmondragon** [comment]
I'm seeing the error even when not going through the Hub but directly in GitHub:

1. Navigate to the file using the GitHub web UI
2. Reload the page - 406 is returned

**Comment by tayloramurphy** [comment]
Ok, sounds like it's a GitHub issue. I'll keep this open but still merge https://github.com/meltano/hub/pull/683/files which is now about changing the whitespace around the link.

**Comment by tayloramurphy** [comment]
Closing as this seems to be sorted.
