### ISSUE TITLE
Ensure `state` capability is included for all that support it

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#689]
Related to this thread in slack https://meltano.slack.com/archives/C01TCRBBJD7/p1659124262172409 and https://github.com/meltano/hub/pull/688.

I've heard users get tripped up by this a bunch of times where our plugin definition doesnt have `state` as a capability so it does a full refresh every time. Then usual path is that the user looks up what singer state is and starts trying to figure out how to store it and pass it into their commands when really the problem is that meltano is unaware of the fact that it should be doing that automatically. This is a pretty painful flow for new users.

We should take a pass at making sure every tap that doesnt have state as a capability actually doesnt have state. It might be a small number of them so solving this could mean writing a quick script to find taps without state and opening up their repos to see if they should get it added. If its a lot we might have to find a different non-manual route.

**Comment by tayloramurphy** [comment]
@pnadolny13 I'm a fan of it. Likely prior to the Hub revamp launch would be a good time. Ideally we could do something automated as well..

**Comment by pnadolny13** [comment]
I realized that now that we have the hub definitions in Snowflake this will be very easy to query for, and we can choose variants with the highest usage first.
