### ISSUE TITLE
Revamp: Clean up Singer pages

### ISSUE THREAD

**Issue by alexmarple** [meltano/hub#691]

**Comment by aaronsteers** [comment]
@rwfeather - Does it make sense to split this into two issues?:

1. Singer content pages.
2. Singer tap/target detail pages.

The detail pages can be redirects to the main extractor/loader detail pages.

The content pages just need to exist and be moderately presentable from a CSS perspective (hopefully made easier by the Tailwind integration in #783).

**Comment by aaronsteers** [comment]
Closing this issue to be replaced by more granular:

- #792 
- #793
