### ISSUE TITLE
Unable to install target-gcs, hub needs to be updated to use the latest version

### ISSUE THREAD

**Issue by jerrydeng** [meltano/hub#708]
I wasn't able to install target-gcs.  The problem is fairly easy to reproduce and it seems to be just needing an update to the hub to reference the latest version from the author.  The referenced tag  of 0.11.3 is no longer in https://github.com/Datateer/target-gcs.git  repository.

Below are the error I received.

```
Added loader 'target-gcs' to your Meltano project
Variant:        datateer (default)
Repository:     https://github.com/Datateer/target-gcs
Documentation:  https://hub.meltano.com/loaders/target-gcs

Installing loader 'target-gcs'...
Loader 'target-gcs' could not be installed: failed to install plugin 'target-gcs'.
  Running command git clone --filter=blob:none --quiet https://github.com/Datateer/target-gcs.git /private/var/folders/99/0v4bp70x0hz59xhx9r07vxlh0000gp/T/pip-req-build-z7naw51i
  WARNING: Did not find branch or tag '0.11.3', assuming revision or ref.
  Running command git checkout -q 0.11.3
  error: pathspec '0.11.3' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q 0.11.3 did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q 0.11.3 did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Failed to install plugin(s)
```

**Comment by pnadolny13** [comment]
@jerrydeng thanks for logging this! I just opened a PR to remove the pinning entirely https://github.com/meltano/hub/pull/712. We're still working out our pattern but right now most hub plugins are unpinned and we recommend users pin a version in their own projects via meltano.yml.

Theres a discussion related to how we pin pip version, here one https://github.com/meltano/meltano/discussions/6445. Feel free to join the conversation if you have opinions!
