### ISSUE TITLE
Hub add same header and footer as .com

### ISSUE THREAD

**Issue by emilylucie** [meltano/hub#709]
<img width="1380" alt="Screen Shot 2022-08-08 at 3 44 22 PM" src="https://user-images.githubusercontent.com/84082383/183511225-8861aa48-6418-4f57-bfa2-66af75927fb6.png">
<img width="1388" alt="Screen Shot 2022-08-08 at 3 44 35 PM" src="https://user-images.githubusercontent.com/84082383/183511227-a68d75f2-96c6-406e-8551-e18875b4b50c.png">

as discussed in the leadership call we agreed to look into adding consistent heads across all our web entities (.com, sdk, hub, docs, maybe handbook). 

### Why do this:

- User experience 
- No dead ends- lost opportunity
- Consistency + branding
- Give people a clearer picture of the Meltano ecosystem 

My suggestion would be to start by just adding the header and footer from the .com pages (above) if that is even possible. If this is not possible, I would create a paired-down version for this purpose. 

### Must haves at a min:
- always linking back to home page
- always has star us- link to github 
- slack link
- social links are a nice to have 
-
<img width="528" alt="Screen Shot 2022-08-08 at 3 52 24 PM" src="https://user-images.githubusercontent.com/84082383/183512431-3dfcc14d-a460-40d3-89b7-8f6bc71f2a3f.png">

**Comment by emilylucie** [comment]
https://github.com/meltano/internal-general/issues/436

**Comment by tayloramurphy** [comment]
@aaronsteers @alexmarple what are your thoughts about pulling this into the Gridsome revamp?

**Comment by aaronsteers** [comment]
@tayloramurphy - I think we need to remain focused on shipping the Revamp first, then can pick this up.

**Comment by tayloramurphy** [comment]
@aaronsteers I'm having our design contractor include elements of this. We'll use the revamp as a jumping off point.

**Comment by emilylucie** [comment]
@aaronsteers @tayloramurphy what is the timeline on the revamp?  This lack of coherence and inability to have lead flow hurts us every day, so I would hate for this to linger much longer. Taylor, does your comment above mean he is working on it right now?

**Comment by alexmarple** [comment]
@aaronsteers @tayloramurphy @emilylucie i'd be curious what brandon's viewpoint on having a consistent header/footer across all of the properties. i feel somewhat opposed to the idea. i'm trying to think of examples where such a thing exists but i can't (if y'all have examples that'd be great). alternatively [mailchimp](https://mailchimp.com/) and their [developer site](https://mailchimp.com/developer/) (which i helped build) share common threads but are entirely different experiences. if our design guru is in the affirmative and can provide us mocks that'd be great.

**Comment by tayloramurphy** [comment]
Closing as I think we're good here.
