### ISSUE TITLE
Change default variant of tap-salesforce

### ISSUE THREAD

**Issue by DouweM** [meltano/hub#716]
The default variant of tap-salesforce (https://hub.meltano.com/taps/salesforce) is currently https://gitlab.com/meltano/tap-salesforce, which we are not actually confident maintaining as we don't have a Salesforce test account.

Unless and until we decide to officially take on the maintenance burden (or share it with the community via `MeltanoLabs`), I think we should change the default to `singer-io`: https://github.com/singer-io/tap-salesforce

**Comment by DouweM** [comment]
@tayloramurphy FYI

**Comment by pnadolny13** [comment]
Cross posting from a slack thread about this, I said:

> For context I worked on finding new non-meltano variants as part of https://gitlab.com/meltano/hub/-/issues/99 and https://gitlab.com/meltano/meltano/-/issues/2969. I cant find the issue comments (maybe its in slack) but we decided to keep the meltano variant over singer-io because it supports user/pass auth instead of key based

**Comment by tayloramurphy** [comment]
https://meltano.slack.com/archives/C02MBDUHCCD/p1655324722211519 is another thread where @aaronsteers and I went back and forth. I'm going to bring this to the leadership meeting to sync on as well.

**Comment by tayloramurphy** [comment]
We've decided we're _not_ going to change the default, but we are moving it from GitLab to MeltanoLabs - tracking in https://github.com/meltano/internal-general/issues/437
