### ISSUE TITLE
Update SqlFluff docs for adapter specific pip_url

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#726]
Based on a slack thread https://meltano.slack.com/archives/C01UTUSP34M/p1660572552731549?thread_ts=1656400983.335709&cid=C01UTUSP34M

The sqlfluff [plugin definition](https://github.com/meltano/hub/blob/93db03886d1b936b45965c2911ddf23966daf455/_data/meltano/utilities/sqlfluff/sqlfluff.yml#L4) only includes `sqlfluff[dbt]` in its pip_url and doesnt have dbt-core but I think its required in order to use it with dbt without error. For example in [squared](https://github.com/meltano/squared/blob/6271f7d9b987c128114dc376618b434e1929b8e4/data/utilities/utilities.meltano.yml#L5) my pip url is `sqlfluff[dbt]==1.2.1; sqlfluff-templater-dbt==1.2.1; dbt-core~=1.1.0;`. It sounds like it fails following an install without it right now.

Was there a reason not to include this?

**Comment by edgarrmondragon** [comment]
@pnadolny13 I think the old way that relied on the pip extra (`sqlfluff[dbt]`), which is no longer recommended installed the old dbt package that included all the common warehouse adapters.

The current right way should include `sqlfluff`, the specific dbt adapter package, and the `sqlfluff-templater-dbt` package. Something like:

https://github.com/edgarrmondragon/meltano-dataops/blob/48fca5e739a67acb6e2186900d95a2bbb61c4503/meltano.yml#L127

**Comment by pnadolny13** [comment]
@edgarrmondragon thanks for that! So we wouldnt want to put a dbt adapter specific pip url in the plugin definition. We can add instructions to append that to the pip url after installation in the hub docs.

Maybe I'll add it as part of https://github.com/meltano/hub/pull/633 also.

**Comment by pnadolny13** [comment]
The work for this is to update https://github.com/meltano/hub/pull/633 based on the feedback and take it across the finish line.
