### ISSUE TITLE
Hub Revamp - Feedback Tracker

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#733]
Opening a thread for formatting and cosmetic feedback on the Hub Revamp.

**Comment by aaronsteers** [comment]
Some logos have a white background instead of transparent background. I'm wondering if we should search around for transparent images, or perhaps just make the page background white?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/18150651/185477979-1834e2fe-1997-446c-9512-2d0714f67e29.png">

**Comment by aaronsteers** [comment]
Monospace font formatting:

1. Should probably just be light-grey or light-blue background or no background color. Could be modeled after exisiting formats on hub.meltano.com or docs.meltano.com. 
2. The 'inline' version of monospace has a large box wrapper, versus the smaller outlines we'd expect for inline formatting.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/18150651/185478280-64d400ee-7860-4fa2-9041-90d33085811d.png">

Example from prior `hub.` formatting:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/18150651/185478458-1ae96423-1831-4fe0-9a36-daa2431c5948.png">

**Comment by aaronsteers** [comment]
Sometimes while searching, clicking on a result may take you to the content without closing the search results.

**Comment by tayloramurphy** [comment]
All variants for a connector shouldn't be listed side-by-side https://meltano-hub-gridsome.netlify.app/extractors/2 We have the https://github.com/meltano/hub/blob/main/_data/default_variants.yml file which specifies which is the main one.

**Comment by tayloramurphy** [comment]
@alexmarple @aaronsteers wanted to note that the commands experience isn't up to parity with the classic hub just yet - https://hub.meltano.com/transformers/dbt-snowflake#commands vs https://meltano-hub-gridsome.netlify.app/transformers/dbt-snowflake/dbt-labs/#commands (not sure if anchor tags work either).

**Comment by alexmarple** [comment]
@tayloramurphy @aaronsteers closing this in favor of the final burndown list ([found here](https://github.com/meltano/hub/discussions/757))
