### ISSUE TITLE
tap-dynamodb add variant dataops-tk

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#743]
Add https://github.com/dataops-tk/tap-dynamodb as dynamodb variant @aaronsteers do you remember the status of this? Maybe we migrate it to MeltanoLabs? It looks like its in better shape than the default singer-io variant and the singer-io variant has many open PRs that dont look theyre being reviewed.

**Comment by aaronsteers** [comment]
@pnadolny13 - Based on what we know now, I would prefer to port this to SDK before migrating over. I was the prior owner of that fork, and I wouldn't have time to address feedback if it is raised.

The biggest challenge with this source is that schema itself is non-deterministic and not scannable.

One simple change would be to encompass the data columns themselves in `record_data` JSON column (variant) for that list of dynamic columns, and maybe something like `key_data` for the tables primary keys. Alternatively or additionally, we could add auto-schema detection as @visch and @edgarrmondragon and others have implemented in other taps.

What we had to do in the past was to create a custom schema catalog by hand, but this is tricky to maintain as you might expect - and tricky to teach to users new to Singer.

**Comment by aaronsteers** [comment]
Also - because I'm not supporting the `dataops-tk` org any longer, a move into `MeltanoLabs` would make sense if/when we want to promote this.

**Comment by pnadolny13** [comment]
@aaronsteers thanks for those details! That all makes sense to me.
