### ISSUE TITLE
chore(gridsome): GraphQL solve for workaround of additional `name` field in plugin `commands`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#761]
@alexmarple - Logging here as a reminder for us to loop back on this issue before merging the cumulative `gridsome-main` branch: #663.

**Comment by alexmarple** [comment]
I think I have a solve for this. I'll try it out in a little while.

**Comment by aaronsteers** [comment]
@rwfeather - For context, this PR took on technical debt in having to add `name:` entries everywhere in the `commands` declarations:

- https://github.com/meltano/hub/commit/b238961ae13a5a57f9866626958ed53e624b9172

![Uploading image.png…]()
