### ISSUE TITLE
add new SDK-based target-snowflake to hub

### ISSUE THREAD

**Issue by kgpayne** [meltano/hub#771]

**Comment by tayloramurphy** [comment]
* https://github.com/MeltanoLabs/target-snowflake/issues/1

**Comment by aaronsteers** [comment]
As discussed:

- Let's go ahead and add.
- We can be humble on maintenance status field and we can add disclaimer in `prereqs` yaml section or similar of known issues.
- If knowns issues are logged, users will be less surprised when they run into them.

**Comment by aaronsteers** [comment]
Update: tap is published to Hub:

- https://hub.meltano.com/extractors/tap-snowflake--meltanolabs/

Target not yet on Hub as of today.

I've updated the title to focus on the target only.

**Comment by pnadolny13** [comment]
@tayloramurphy Its already on the hub https://hub.meltano.com/loaders/target-snowflake--meltanolabs/ ! I added it a couple weeks ago in https://github.com/meltano/hub/pull/1179.
