### ISSUE TITLE
Use tailwind.css

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/hub#783]
[tailwind](https://tailwindcss.com/) will make styling much easier and enable quicker development and provides a lot of useful utility classes for easy responsive UI.

Gridsome has [a plugin](https://gridsome.org/plugins/gridsome-plugin-tailwindcss) to make this easier.

**Comment by rwfeather** [comment]
Agree that tailwind will set us up a lot better for styling and layouts.

**Comment by aaronsteers** [comment]
@cjohnhanson - Thanks for logging. I think this makes sense to add sooner than later. To follow the principal of not having 'unused code paths', I recommend we add the tailwind library at the same time as implementing it in one or more locations, in order to improve layout or to improve rendering of our grid view results, for instance.

**Comment by aaronsteers** [comment]
@cjohnhanson and @rwfeather - Should we still do this one?:

- https://github.com/meltano/hub/issues/762

And if so, should we combine 'adding `saas` support' with 'adding `tailwind` support' together as the same PR?

**Comment by cjohnhanson** [comment]
@aaronsteers I'll defer to @rwfeather for final 👍 /👎 but I think tailwind has enough support for theming that we probably don't need sass/scss. We would just configure our colors and fonts once in `tailwind.config.js` and then just use tailwind's classes.

**Comment by rwfeather** [comment]
Yeah, I agree. Tailwind as our theming layer seems good.

Also, FWIW I think sass already works in our current configuration, no work necessary. Tried it out earlier today and renaming `main.css` to `main.scss` had no issues, and we already are writing scss inside the Vue components.

So if we do run into something moving forward that can only be solved with sass variables/imports, I think we should be fine.
