### ISSUE TITLE
fix(gridsome): hover menus display partially out of viewport 

### ISSUE THREAD

**Issue by rwfeather** [meltano/hub#784]
![Screen Shot 2022-09-13 at 7 31 13 PM](https://user-images.githubusercontent.com/6589528/190032673-fddfe251-dd59-45ce-bd3d-918177a129e8.png)

**Comment by rwfeather** [comment]
Might be easier once we have #783 

Could possibly wait till after release.

**Comment by aaronsteers** [comment]
Per feedback from @tayloramurphy, let's simplify to remove the extra description and just do a single column menu drop-down. Like existing hub flyout:

![image](https://user-images.githubusercontent.com/18150651/190816022-38e503e1-01ca-4326-94c6-caeb0c4e67b6.png)

![image](https://user-images.githubusercontent.com/18150651/190816079-5ecc32e1-744f-4d58-a9bc-12076af678ce.png)

**Comment by WillDaSilva** [comment]
Implemented in e03278f11cf88c2c6ae4ccd33a22e993edba184f

**Comment by aaronsteers** [comment]
Resolved in #813
