### ISSUE TITLE
fix(gridsome): plugin detail sidebar shouldn't float to bottom on small screen widths

### ISSUE THREAD

**Issue by rwfeather** [meltano/hub#785]
Perhaps a better compromise would be having it move above the main content once the screen width makes it hard to have a sidebar.

**Comment by aaronsteers** [comment]
@rwfeather - Agreed - I think if out of space, it makes more sense to move _above_ the main content. That's similar to how the Jekyll site renders today:

- e.g.: https://hub.meltano.com/extractors/tap-abcfinancial

**Comment by aaronsteers** [comment]
@rwfeather, @cjohnhanson, FYI, I'm bumping this up into MVP milestone because the sidebar is now static at the bottom and seems to be stuck in a too-small width.
