### ISSUE TITLE
change(gridsome): Drop the legacy tap/target API endpoints

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#790]
We are no longer supporting a Singer-specific JSON API so we can probably remove that in our Gridsome Revamp.

@tayloramurphy - can you confirm?

This would mean deleting:

- https://hub.meltano.com/singer/taps.json
- https://hub.meltano.com/singer/targets.json
- https://hub.meltano.com/singer/schema.json

**Comment by tayloramurphy** [comment]
@aaronsteers it's still a goal of ours to have a Singer-specific endpoint for taps and targets. We still publicly state that here https://hub.meltano.com/singer/docs#api. I'd like to be able to offer those endpoints, all still driven by the same YAML file.

**Comment by aaronsteers** [comment]
Circling back to this after our call yesterday.

As discussed, I think we can safely remove since as of yet, we don't believe there are dependencies on this format - but we'll raise to leadership for confirmation.

**Comment by aaronsteers** [comment]
As noted in https://github.com/meltano/hub/issues/793#issuecomment-1254240358:

> @rwfeather - We are approved to remove these:
> 
> 1. The JSON API endpoints for taps and targets. (Users will be recommended to use the newer API which covers _all_ meltano plugin types.)
> 2. The Singer tap/target index and detail pages. (Redirect to 'extractor'/'loader' equivalents.)
>    
>    * Related follow-on: [feat(gridsome): add "standalone usage" section to main plugins pages #821](https://github.com/meltano/hub/issues/821)

**Comment by aaronsteers** [comment]
Resolved in #791
