### ISSUE TITLE
change(gridsome): Card view or similar for index page grids

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#800]
The index page layout is too tight as of now.

1. Entries in the matrix should have some padding to space entries between each other.
2. The icon space for each should used a fixed hight buffered by white space as needed, along with a max width.
   - This should force a consistent starting `y` position for each item's label in a row.
4. The hover animation should not resize or relocate items beneath or around the selected item.
5. As page resizes, num cols in each row should be constant. (Resize from 5 items per row down to 4 items per row should affect _all_ rows at the same time.

@tayloramurphy - Can you attach the designer's mockup?

**Comment by tayloramurphy** [comment]
<img width="248" alt="Screen Shot 2022-09-16 at 6 30 51 PM" src="https://user-images.githubusercontent.com/5394188/190830383-fdfeb542-5cf6-4924-88e4-35f2dab64073.png">
<img width="730" alt="Screen Shot 2022-09-16 at 6 30 57 PM" src="https://user-images.githubusercontent.com/5394188/190830384-f9acdaed-9730-4d4d-9f33-005ec19ffb5d.png">


I like keeping it at 4 across max given our current windowing,

**Comment by aaronsteers** [comment]
Super helpful - thanks, @tayloramurphy !

**Comment by aaronsteers** [comment]
@cjohnhanson - Is this something you'd be interested in picking up? Doesn't have to exactly match the above but would be good to get a little closer before launch.

**Comment by cjohnhanson** [comment]
@aaronsteers yeah I can pick this up, I'll take a look this afternoon.

**Comment by aaronsteers** [comment]
Thanks! 👍

**Comment by cjohnhanson** [comment]
@aaronsteers Got started on this today and I think both this and #803  should be relatively straightforward (though with a lot of experimentation) with tailwind. I think I can have PRs ready for both no later than Wednesday.

**Comment by aaronsteers** [comment]
Great news. Thanks, @cjohnhanson !

**Comment by aaronsteers** [comment]
Resolved in #809
