### ISSUE TITLE
change(gridsome): Cleanup search results rendering

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#803]
Here's a sample output from our work with a designer.

![image](https://user-images.githubusercontent.com/18150651/190832514-4bb75038-b39d-4889-b00e-c93913a7f135.png)

1. The icon consumes the left-most square of the grid.
2. The label section can be brought to the side of the icon.
3. The plugin type can be left-aligned after the title, optionally with a 'badge' rendering.

Currently we have: 

![image](https://user-images.githubusercontent.com/18150651/190832880-c5a861c1-19ac-4217-86cb-ff04e889b699.png)

**Comment by aaronsteers** [comment]
@cjohnhanson - Do you have capacity to take a pass as this next week in addition to #800. As with #800, we don't need to get to a perfect match against the long-term design, but a little cleanup would go a long way.

cc @tayloramurphy

**Comment by cjohnhanson** [comment]
@aaronsteers ditto as with #800, I'll take a look this afternoon and have a plan + time estimate for both by EoD

**Comment by aaronsteers** [comment]
Thanks, @cjohnhanson !

**Comment by aaronsteers** [comment]
Resolved in #814
