### ISSUE TITLE
feat(gridsome): New top-left logo: "Meltano | Hub"

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#810]
We have a proposed design for the top-left logo:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/18150651/191184370-227bd3fd-f4d5-4ed0-b7f2-52ddc5e8a752.png">

@tayloramurphy - can you link to the relevant image asset(s)?

**Comment by aaronsteers** [comment]
@tayloramurphy - Do you mind attaching the image assets if you have them? Thanks!

**Comment by tayloramurphy** [comment]
@aaronsteers Meltano logos are in https://drive.google.com/drive/u/1/folders/1p-kDiycE5qvQxwtlMBQuvn1xbd-8d9pN

The `| Hub` in Figma is IBM Plex Sans, 40px size, 600 weight.

**Comment by aaronsteers** [comment]
Thanks, @tayloramurphy !

**Comment by aaronsteers** [comment]
@tayloramurphy - FYI, I've moved the logo into "Day 2". My goal by adding to MVP was that we might have gotten to it in the mob session, but I don't think it's worth blocking on at this point. Does that sound okay to you too?

**Comment by tayloramurphy** [comment]
@aaronsteers I do think it's worth doing before launch. Getting the logo right is important and what's currently in the preview is a step backwards from what's on the Classic Hub.

**Comment by tayloramurphy** [comment]
@cjohnhanson any chance you could slip this in? AJ requested I ping you on this. The asset + font should be in this comment https://github.com/meltano/hub/issues/810#issuecomment-1253942935
