### ISSUE TITLE
feat(gridsome): improve markdown page rendering

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#815]
Known issues as of now with markdown page rendering:

- [x] Syntax highlighting for code blocks does not appear to be working as of yet.
- [x] The content `div` is left-aligned, wheras it should instead be either full-width or centered with a border on either side.
- [x] We should add back ~~borders~~ anchors as/when we're able.
- [ ] We should add back the right-hand TOC nav as/when we're able.

As of now, this only affects two pages:

- `/singer/docs`
- `/singer/spec`

_Originally posted by @aaronsteers in https://github.com/meltano/hub/issues/813#issuecomment-1253200005_

**Comment by rwfeather** [comment]
@aaronsteers I have a PR ready for the first 2 items.

Not sure what the black border is referring to, just a solid outline around the whole content section?

I've done some quick checking on what it would take to make a TOC. https://github.com/remarkjs/remark-toc exists but it might be challenging to get it to render onto the side rather than within the content.

**Comment by aaronsteers** [comment]
@rwfeather - Re:

> Not sure what the black border is referring to

On rereading my own comment, I this was an autocorrect glitch. Should have read:

> - [ ] We should add back ~~borders~~ anchors as/when we're able.

Sorry for the confusion - thumb-typo fail! 🤦  🙃

**Comment by rwfeather** [comment]
@aaronsteers that makes sense, I think I can slip it into this PR real quick

**Comment by aaronsteers** [comment]
> I've done some quick checking on what it would take to make a TOC. [remarkjs/remark-toc](https://github.com/remarkjs/remark-toc) exists but it might be challenging to get it to render onto the side rather than within the content.

These pages don't need to be perfect at launch. An automated TOC of any type is a big help and I definitely wouldn't block on it either way.

**Comment by aaronsteers** [comment]
> @aaronsteers I have a PR ready for the first 2 items.

Exciting! I think those are the most important from this list. 👍

**Comment by aaronsteers** [comment]
Closing this as resolved. Thanks, @rwfeather. 

I've created a separate issue to track the TOC as lower pri:

- https://github.com/meltano/hub/issues/828
