### ISSUE TITLE
Gridsome: Follow-up from plugin index updates (#809)

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#816]
> @cjohnhanson looks like a great iteration. My notes:
> 
> * [x] the pagination issue AJ already mentioned
> * [x] The height of each of the grids is dependent on a row based on the largest icon on that row. I think it's most noticeable on the loaders page where the shift in the cards between rows is more obvious https://deploy-preview-809--meltano-hub-gridsome.netlify.app/loaders/ I think just using the same size across the board would be cleanest?
> * [ ] Is there a setting to have an incomplete row be centered? https://deploy-preview-809--meltano-hub-gridsome.netlify.app/orchestrators feels weird

_Originally posted by @tayloramurphy in https://github.com/meltano/hub/issues/809#issuecomment-1252541212_

**Comment by cjohnhanson** [comment]
Closed in #819
