### ISSUE TITLE
chore: check GA metrics from Gridsome site

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#826]
Follow-up from #808:

> Approving... Will open another issue to confirm that telemetry is coming through, and in the meanwhile we are seeing about getting @rwfeather access to GA so she can review directly.

_Originally posted by @aaronsteers in https://github.com/meltano/hub/pull/808#pullrequestreview-1116214729_

**Comment by rwfeather** [comment]
From @pnadolny13's [comment](https://github.com/meltano/hub/pull/808#issuecomment-1255049475) in the orignal PR, it seems like this may already be confirmed. We should now have GA stats coming in from hub.meltano.com after the release.

**Comment by aaronsteers** [comment]
Thanks, @rwfeather !

Closing ...
