### ISSUE TITLE
bug(gridsome): "edit on github" links should use plural plugin type text for URL

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#831]
Example page: https://meltano-hub-gridsome.netlify.app/extractors/tap-carbon-intensity/

"Edit on GitHub" leads to:

- https://github.com/meltano/hub/blob/main/_data/meltano/extractor/tap-carbon-intensity/meltano.yml

Instead of:

- https://github.com/meltano/hub/blob/main/_data/meltano/extractors/tap-carbon-intensity/meltano.yml

**Comment by edgarrmondragon** [comment]
Was this addressed by https://github.com/meltano/hub/pull/832?

**Comment by aaronsteers** [comment]
Yes, thanks, @edgarrmondragon . Looks like those were not linked.

Closing as resolved, per #832.
