### ISSUE TITLE
feat(gridsome): Add more details to settings section

### ISSUE THREAD

**Issue by rwfeather** [meltano/hub#846]
Right now we are still missing a few things from old hub:

![Screen Shot 2022-09-27 at 10 03 52 AM](https://user-images.githubusercontent.com/6589528/192563380-4b64ffd5-158d-4f92-8380-1e8afdd9c03e.png)

- Environment variable form
- Default value
- "How to Use" section

**Comment by tayloramurphy** [comment]
target-redshift is a good example to review as well https://github.com/meltano/hub/blob/main/_data/meltano/loaders/target-redshift/transferwise.yml https://hub.meltano.com/loaders/target-redshift

Confirming key things to display:
* environment variable form `<plugin_name>_<setting_name>`
* default value
* description (in YAML file)
* How to use section can be autogenerated based on the setting name and either the default or the kind (integer, password, etc.)

**Comment by tayloramurphy** [comment]
> How to use section can be autogenerated based on the setting name and either the default or the kind (integer, password, etc.)

From #663 - I'm not sold that we _shouldn't_ have this section as-is, but currently there are no instructions on the preview. I'm fine with either recreating what we have or having instructions on setting with --interactive, but we need to have _something_. We can take another post-launch iteration on what we want there for each setting. @aaronsteers @rwfeather does that work?

**Comment by aaronsteers** [comment]
@tayloramurphy - How about a simple "Configuration" header after settings list, with instructions for `--interactive` as per the below:


> ## Settings
> 
> The `dbt-postgres` settings that are known to Meltano are documented below. To quickly find the setting you're looking for, click on any setting name from the list:
> 
> [project_dir](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#project_dir-setting)
> [profiles_dir](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#profiles_dir-setting)
> [host](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#host-setting)
> [user](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#user-setting)
> [password](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#password-setting)
> [port](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#port-setting)
> [dbname](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#dbname-setting)
> [schema](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#schema-setting)
> [keepalives_idle](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#keepalives_idle-setting)
> [search_path](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#search_path-setting)
> [role](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#role-setting)
> [sslmode](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#sslmode-setting)
> 
> You can [override these settings or specify additional ones](https://docs.meltano.com/guide/configuration#overriding-discoverable-plugin-properties) in your `meltano.yml` by adding the `settings` key.
> 
> Please consider adding any settings you have defined locally to this definition on MeltanoHub by making a [pull request to the YAML file](https://deploy-preview-663--meltano-hub.netlify.app/transformers/dbt-postgres#contributing).
> 
> ## Configuration
> 
> All of the below settings can be configured by running `meltano config set {plugin_name} --interactive`
> 
> [...Dynamic settings list here...]

But instead of `{plugin_name}`, it would be the actual plugin name. I can mock this up real quick if this works for you.

**Comment by aaronsteers** [comment]
A small alteration on the paragraph above could be:

> All plugin settings can be [configured](https://docs.meltano.com/reference/command-line-interface#config) by running `meltano config set {plugin_name} --interactive` or with [environment variables](https://docs.meltano.com/guide/configuration#configuring-settings).

This gives users a clear and simple suggestion to use `--interactive`, while also sending them to the appropriate pages to learn more if they want to do it another way. While it's a critical feature for advanced users, I don't really want to be promoting env variables in the Hub because it leads to confusion in the new-user experience, when we want users to have a clear "golden path" without unnecessary distractions or hurdles.

**Comment by tayloramurphy** [comment]
@aaronsteers love that suggestion and it works for me 👍
