### ISSUE TITLE
Mobile search experience doesn't render while typing

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#863]
On mobile, it seems the search experience doesn't start to render until the space or enter key is pressed on the keyboard.

_Originally reported by @visch in https://github.com/meltano/hub/discussions/818#discussioncomment-3776066_

**Comment by rwfeather** [comment]
Unfortunately, this Is not affecting my iPhone 12, and I can't seem to reproduce using chrome devtools screen sizing tool either.

It might need someone with an android phone or and emulator set up

**Comment by aaronsteers** [comment]
@rwfeather - it may be related to the browser not sending results until autocorrect settings are chosen. I noticed that tapping the suggestion (thereby exiting the 'under evaluation for replacement' status) also sent the query.

**Comment by rwfeather** [comment]
That seems like the case yeah. I've dug up a similar example: https://stackoverflow.com/questions/49791906/vue-js-android-keyboard-the-last-typed-word-is-missing-on-the-model

Let me get that workaround in a preview branch so someone can verify the fix.
