### ISSUE TITLE
bug: Incorrect description on non-singer plugin pages

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#864]
It looks like non-tap/target plugins like Superset are getting an incorrect description on their plugin pages describing them with default Singer wording i.e. syncs data from x to y.

<img width="942" alt="Screen Shot 2022-10-02 at 5 50 01 PM" src="https://user-images.githubusercontent.com/27376735/193477827-eeb603ff-4770-4d76-ae18-3b8573c7e1f4.png">

**Comment by aaronsteers** [comment]
@pnadolny13 - Thanks for raising. Should be an easy fix. 👍

**Comment by tayloramurphy** [comment]
I wonder if something was accidentally reverted... I definitely remembered this working properly in the preview.

**Comment by tayloramurphy** [comment]
@aaronsteers can we get this prioritized for next week?

**Comment by pnadolny13** [comment]
Also wanted to flag https://github.com/meltano/hub/issues/885 since its probably the same fix but that one calls out singer plugin page descriptions being incorrect also.
