### ISSUE TITLE
Hub Reviewer for a Month

### ISSUE THREAD

**Issue by tayloramurphy** [meltano/hub#884]
@aaronsteers we've talked about this in the past but never opened an issue for it. The way I'm imagining this is that we could assign the issue to an engineer with the general mandate to go through all parts of MeltanoHub (connectors, docs, metadata, etc) to find and fix any bugs and usability issues they see. A particular focus on the top targets to make sure the documentation is clear and everything is as up to date as it can be.

Do you think we could get this assigned ASAP to get a cycle in prior to Taptoberfest?

**Comment by aaronsteers** [comment]
@tayloramurphy - 

1. If it's ok with you, I think I lean towards making this a group/mob exercise in our first pass at least. We can schedule something this week. If we start with the list of top 30 plugins, we can divide them up and each take 3-5. Some should be simple and have no issues, while others may have missing docs, incorrect capabilities listed, etc.
2. We should probably consider merging my hackday slash command tests before picking this up, as that significantly reduces the effort needed for testing each plugin.
3. To make sure we make adequate progress on both without being overly randomized, I'd like to sharply distinguish the general site changes from the review/update of the plugin definitions themselves. Can we open another issue for general site/usability issues outside of the plugin definitions themselves? (If we know what the issues are, and even if we don't, @sbalnojan might be the best one to own or at least raise those issues.)

What do you think?

**Comment by tayloramurphy** [comment]
@aaronsteers mob bashing would achieve the same goal I think! And agreed that this should be more focused on the content of the connectors / docs and less on the actual usability / changes in the site itself 👍

**Comment by aaronsteers** [comment]
- #886
