### ISSUE TITLE
Mob Session: Hub Definition Updates

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#892]
Tacking issue for Oct 13 mob session re: plugin definition updates.

PR: https://github.com/meltano/hub/pull/895
Spreadsheet: https://docs.google.com/spreadsheets/d/1PdM1Mp-PMF6V1r1gbI7d1qcJzGPtbqgmCOMjbdj4drI/edit#gid=1111558337

**Comment by aaronsteers** [comment]
/test-plugin name=tap-github pip-url=git+https://MeltanoLabs/tap-github.git@main

**Comment by aaronsteers** [comment]
/test-plugin name=tap-github pip-url=git+https://github.com/meltanolabs/tap-github.git@main

**Comment by aaronsteers** [comment]
/test-plugin name=tap-github pip-url=git+https://github.com/meltanolabs/tap-github.git@main

**Comment by aaronsteers** [comment]
/test-plugin name=tap-github pip-url=git+https://github.com/meltanolabs/tap-github.git@main

Note: github collapses the text `https://github.com/` when rendering the above. The actual full command is:

`/test-plugin name=tap-github pip-url=git+https://github.com/meltanolabs/tap-github.git@main`

**Comment by tayloramurphy** [comment]
/test-plugin name=target-yaml pip-url=git+https://github.com/MeltanoLabs/target-yaml.git

**Comment by WillDaSilva** [comment]
/test-plugin name=target-postgres pip-url=pipelinewise-target-postgres

**Comment by aaronsteers** [comment]
/test-plugin name=tap-carbon-intensity pip-url=git+https://gitlab.com/meltano/tap-carbon-intensity.git

**Comment by WillDaSilva** [comment]
/test-plugin name=target-snowflake pip-url=pipelinewise-target-snowflake

**Comment by pandemicsyn** [comment]
/test-plugin name=target-csv pip-url=git+https://github.com/hotgluexyz/target-csv.git

**Comment by edgarrmondragon** [comment]
/test-plugin name=tap-spreadsheets-anywhere pip-url=git+https://github.com/ets/tap-spreadsheets-anywhere.git

**Comment by pandemicsyn** [comment]
/test-plugin name=tap-csv pip-url=git+https://github.com/MeltanoLabs/tap-csv.git

**Comment by edgarrmondragon** [comment]
/test-plugin name=tap-google-analytics pip-url=git+https://github.com/MeltanoLabs/tap-google-analytics.git

**Comment by edgarrmondragon** [comment]
/test-plugin name=tap-hubspot pip-url=git+https://github.com/singer-io/tap-hubspot.git

**Comment by edgarrmondragon** [comment]
/test-plugin name=tap-airtable pip-url=git+https://github.com/goes-funky/tap-airtable.git

**Comment by edgarrmondragon** [comment]
> /test-plugin name=tap-airtable pip-url=git+[goes-funky/tap-airtable.git](https://github.com/goes-funky/tap-airtable.git)
> 
> > [Starting test job...](https://github.com/meltano/hub/actions/runs/3245172179)
> > ...
> > Job completed.
> 
> Usage info
> Detected capabilities
> > * ✅ 'catalog'
> > * ✅ 'state'
> > * ❌ 'about'

@aaronsteers this one's a false positive for the `state` capability: https://github.com/goes-funky/tap-airtable/blob/46b9b3e010abdc4bde84e38a1fdf4dd0411ee121/tap_airtable/__init__.py#L11-L17

**Comment by aaronsteers** [comment]
@edgarrmondragon - thanks for raising. It looks like our heuristic is fine (screenshot below) but perhaps a case where the developer perhaps started as a copy of another repo and never removed the `--state` flag from the CLI.

![image](https://user-images.githubusercontent.com/18150651/195701462-e59d163d-1675-46cc-b6c4-5b054cf895db.png)

**Comment by edgarrmondragon** [comment]
@aaronsteers I guess that's an issue even for SDK-based taps. There may be some sources that don't really support state, but it will still declare the `state` capability and show it in the `--help` output.

**Comment by aaronsteers** [comment]
@edgarrmondragon - Thanks for calling this out. You prompted me to do an analysis of capabilities [here](https://github.com/meltano/sdk/discussions/1071).

I didn't see any big risks or issues in that analysis. What I realized when writing that was that, even if none of a tap's streams support incremental, there may still be value in accepting a state file via `--state`. State files also can contain elements such as 'last sync time' - and while not adding a ton of value, I don't see a strong reason to reject the file or fail the process if `--state` is passed to the tap.
