### ISSUE TITLE
Add Repo Badge - Last Updated At

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#896]
I noticed that we no longer have a badge for "Last Updated At" date for the repo. I found those useful for quickly seeing if the repo has been inactive for a while.

![Screen Shot 2022-10-13 at 2 21 59 PM](https://user-images.githubusercontent.com/27376735/195676005-08aa329f-45f0-405f-9f91-7a17262f6d6c.png)

**Comment by aaronsteers** [comment]
New PR here to address: #1138
