### ISSUE TITLE
Hide "hidden: true" variants from plugin info pages

### ISSUE THREAD

**Issue by cjohnhanson** [meltano/hub#897]
Hidden plugins don't show up in search results or plugin index pages, but still show up in the "Other available variants" for non-hidden variants of the same target. We should hide these.

Example: https://hub.meltano.com/loaders/target-postgres
The now-defunct `meltano` variant is showing up in the transferwise variant page.

**Comment by WillDaSilva** [comment]
Another example: https://hub.meltano.com/loaders/target-snowflake--meltano/

**Comment by cjohnhanson** [comment]
From Zoom: Hidden variants should still have pages generated for them, but those pages should contain a disclaimer indicating that the plugin is not supported and should point users towards the default variant for the plugin.

Basically, pages should exist but we shouldn't "advertise" them.
