### ISSUE TITLE
Plugin's `settings_preamble` is not rendered in the plugin page

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/hub#909]
For example, [`dbt-bigquery`](https://github.com/meltano/hub/blob/ff09ec2279c7dc3bee05be116f61e47ebee680a1/_data/meltano/transformers/dbt-bigquery/dbt-labs.yml#L14-L15) has it defined

https://github.com/meltano/hub/blob/ff09ec2279c7dc3bee05be116f61e47ebee680a1/_data/meltano/transformers/dbt-bigquery/dbt-labs.yml#L14-L15

but it's not being rendered in https://hub.meltano.com/transformers/dbt-bigquery#settings

**Comment by tayloramurphy** [comment]
Closed via https://github.com/meltano/hub/pull/914
