### ISSUE TITLE
From detail page, clicking header logo only takes to homepage after 2 clicks

### ISSUE THREAD

**Issue by DouweM** [meltano/hub#921]
From https://hub.meltano.com/loaders/target-duckdb/, the first click on the logo changes the URL to https://hub.meltano.com/ but doesn't actually change the page, which only happens upon a second click.

**Comment by tayloramurphy** [comment]
@DouweM I'm not able to reproduce 🤔 @meltano/engineering anyone else?

**Comment by WillDaSilva** [comment]
@tayloramurphy I have reproduced the issue.

**Comment by tayloramurphy** [comment]
@WillDaSilva I've got https://github.com/meltano/hub/pull/926 which replaces the logo  and drops the Hub section, so maybe that will help solve it. I'm not happy with the PR as it is though b/c the logo is a bit smaller than the current one, so not sure if we can bump up the size on that somehow (that's beyond my skills though)
