### ISSUE TITLE
Some plugins have more than one default

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/hub#927]
https://hub.meltano.com/extractors/tap-shopify

<img width="808" alt="Screen Shot 2022-10-14 at 12 34 27" src="https://user-images.githubusercontent.com/16805946/195907301-b47f1909-63b1-4aa1-9e4d-dd10dd3ffcb5.png">

**Comment by tayloramurphy** [comment]
Duplicate of https://github.com/meltano/hub/issues/898

**Comment by tayloramurphy** [comment]
@edgarrmondragon I updated the title of the other one to be more clear. 😄
