### ISSUE TITLE
bug: tap-prometheus install fails

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#941]
The tap listed as default has an invalid dependency https://hub.meltano.com/extractors/tap-prometheus.

```
ERROR: Could not find a version that satisfies the requirement promalyze==0.0.2 (from tap-prometheus) (from versions: 0.0.1)
ERROR: No matching distribution found for promalyze==0.0.2
```

**Comment by edgarrmondragon** [comment]
It's using a fork of `promalyze`

> Module based on the patched python Prometheus API client promalyze: https://github.com/JustEdro/promalyze Load it and install directly (python setup.py install) first.

and [using the deprecated `dependency_links` in `setup.py`](https://github.com/miroapp/tap-prometheus/blob/f68353a5c16cf79159c91ac72470e2f74dac0526/setup.py#L12-L19):

```python
      install_requires=[
          'singer-python==5.2.3',
          'promalyze==0.0.2',
          'pytz'
      ],
      dependency_links=[
          'git+https://github.com/miroapp/promalyze.git#egg=promalyze-0.0.2',
      ],
```

After pip 18.1, [PEP 508](https://peps.python.org/pep-0508/) should be used:

```diff
        install_requires=[
            'singer-python==5.2.3',
-           'promalyze',
+           'promalyze @ git+https://github.com/miroapp/promalyze.git#egg=promalyze-0.0.2',
            'pytz'
        ],
-       dependency_links=[
-           'git+https://github.com/miroapp/promalyze.git#egg=promalyze-0.0.2',
-       ],
```

**Comment by pnadolny13** [comment]
We should add https://github.com/signal-ai/tap-prometheus potentially as the default to resolve this issue.
