### ISSUE TITLE
New tap onboarding: `tap-sharepointsites`

### ISSUE THREAD

**Issue by aaronsteers** [meltano/hub#943]
From @radbrt:

- https://github.com/radbrt/tap-sharepointsites

**Comment by aaronsteers** [comment]
/test-plugin name=tap-sharepointsites pip_url=git+https://github.com/radbrt/tap-sharepointsites.git

**Comment by aaronsteers** [comment]
/test-plugin name=tap-sharepointsites pip-url=git+https://github.com/radbrt/tap-sharepointsites.git

**Comment by edgarrmondragon** [comment]
Erroring in https://github.com/radbrt/tap-sharepointsites/blob/e9f214f77f2a36013e06f37374cdd885a15ccfb9/tap_sharepointsites/tap.py#L26-L31. Needs to include the wrapped type:

```diff
          th.Property(
              "lists",
-             th.ArrayType,
+.            th.ArrayType(th.StringType),
              required=True,
              description="The name of the list to sync"
          ),
```

**Comment by radbrt** [comment]
Great to see the activity here, just a small implementation detail first: My employer might want to host this in their GitHub, I'll check with them tomorrow and report back.

In the meantime, we can of course do all the fixes on the current repo.

**Comment by radbrt** [comment]
The tap has a new home 🥳 https://github.com/storebrand/tap-sharepointsites

Let the onboarding continue. cc @aaronsteers @edgarrmondragon 

(I have a separate github account for work, @hholgersen, in case there is any confusion)

**Comment by edgarrmondragon** [comment]
/test-plugin name=tap-sharepointsites pip-url=git+https://github.com/storebrand/tap-sharepointsites.git

**Comment by aaronsteers** [comment]
/test-plugin name=tap-sharepointsites pip_url=https://github.com/storebrand/tap-sharepointsites.git

(I think the issue was just pip_url vs pip-url. Sidebar: not super intuitive that the command is kabab-case but the param is snake_case.)

**Comment by aaronsteers** [comment]
/test-plugin name=tap-sharepointsites pip-url=https://github.com/storebrand/tap-sharepointsites.git

**Comment by aaronsteers** [comment]
Looks like small regression when we added automated execution upon changes to the underlying yaml files. This is falling back to name but should first check if pip-url slash command arg is missing.

https://github.com/meltano/hub/blob/main/.github/workflows/test-plugin-command.yml#L46

**Comment by radbrt** [comment]
Nothing like debugging ci/cd. That being said, I'm working on adding the package to pypi.

**Comment by radbrt** [comment]
On pypi: https://pypi.org/project/tap-sharepointsites/

**Comment by edgarrmondragon** [comment]
/test-plugin name=tap-sharepointsites pip-url=tap-sharepointsites

**Comment by edgarrmondragon** [comment]
> Looks like small regression on the GitHub Actions side when we added automated execution upon changes to the underlying yaml files. This is falling back to name but should first check if pip-url slash command arg is missing.
> 
> [`main`/.github/workflows/test-plugin-command.yml#L46](https://github.com/meltano/hub/blob/main/.github/workflows/test-plugin-command.yml?rgh-link-date=2022-10-25T17%3A00%3A27Z#L46)

@aaronsteers a related bug is https://github.com/meltano/hub/issues/960

**Comment by radbrt** [comment]
Is there anything I need to do here @edgarrmondragon ? It looks like the tests passed, don't know what the next step is.

**Comment by edgarrmondragon** [comment]
@radbrt next step is to start a PR that adds `tap-sharepointsites` to the `_data` directory

cc @pnadolny13
