### ISSUE TITLE
bug: PR auto test fails on fork PRs

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#969]
https://github.com/meltano/hub/actions/runs/3326476744/jobs/5500226517

I think the test job is failing because the PR is from a fork that it cant access. I'm not sure how we can handle this better other than excluding these tests on forks.

**Comment by pnadolny13** [comment]
cc @WillDaSilva I know these bugs are lower priority but wanted to log it.

**Comment by WillDaSilva** [comment]
> I'm not sure how we can handle this better other than excluding these tests on forks.

Ensuring that it could run on forks was a priority when I made it. This is unexpected behaviour.

> I know these bugs are lower priority but wanted to log it.

Thanks.
