### ISSUE TITLE
bug: target-apprise `AutoIDM` generated docs link broken

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#980]
Related to slack thread https://meltano.slack.com/archives/C047R5W9EKX/p1666976328688719

The API response for target-apprise (AutoIDM) includes a docs link that doesnt match the url pattern of the actual docs, so you get a 404 if you follow it.

- plugin definition file variant: target-apprise, [AutoIDM](https://github.com/meltano/hub/blob/a599ea85c8569148214ae57f4f052f45720fe5a9/_data/meltano/loaders/target-apprise/AutoIDM.yml#L8) variant  in mixed case.
- plugin page variant specific url: `https://hub.meltano.com/loaders/target-apprise--auto-idm/`
- API url: `https://hub.meltano.com/meltano/api/v1/plugins/loaders/target-apprise--AutoIDM`
- docs link from the API definition response: `https://hub.meltano.com/loaders/target-apprise--AutoIDM`

API response:

```
{
    "description": "Apprise allows you to send a notification to almost all of the most popular notification services available to us today such as: Telegram, Discord, Slack, Amazon SNS, Gotify, etc",
    "label": "Apprise",
    "name": "target-apprise",
    "logo_url": "https://hub.meltano.com/assets/logos/loaders/apprise.png",
    "namespace": "target_apprise",
    "variant": "AutoIDM",
    "pip_url": "target-apprise",
    "repo": "https://github.com/AutoIDM/target-apprise",
    "capabilities": [
        "about",
        "stream-maps",
        "record-flattening"
    ],
    "settings_group_validation": [
        [
            "uris"
        ]
    ],
    "settings": [
        {
            "name": "uris",
            "kind": "array",
            "label": "URIs",
            "description": "Array of apprise URIs"
        }
    ],
    "docs": "https://hub.meltano.com/loaders/target-apprise--AutoIDM"
}
```

Potential Solutions:
1. It looks like all other Auto IDM variants are using lowercase variant names like `autoidm` and I dont see any other mixed case variants across the hub. We can force variants to be lowercase and enforce it using our JSON schema in https://github.com/meltano/hub/blob/a599ea85c8569148214ae57f4f052f45720fe5a9/schemas/common/common.schema.json#L96. We could add a regex pattern that allows lowercase and hyphens only.

```
        "variant": {
            "type": "string",
            "pattern": "^[a-z\\-]+(\\d+)*$",
            "description": "The same of the variant.",
            "examples": [
                "singer-io"
            ]
        }
```
2. Update the hub code thats generating the docs links to make sure theyre lowercased appropriately to match the logic used in generating the url paths for variant plugin pages.

I prefer option 1 because it makes everything more consistent vs having some mixed case variant name + a lowercase url path. I think we also usually try to lowercase the variant names so right now theyre inconsistently lowered in some places but not all.

cc @z3z1ma I think this is why your VS code demo hit a 404.

**Comment by aaronsteers** [comment]
@pnadolny13 - thanks for raising. I think we added a CI check a while back to verify that the `variant` text is in the list of maintainers's IDs under maintainers.yml. Do I remember that correctly?

If that's in place, perhaps we should double check that the lookup validation is case sensitive.

**Comment by pnadolny13** [comment]
@aaronsteers yeah good point it looks like we're lowercasing for the comparison there https://github.com/meltano/hub/blob/a599ea85c8569148214ae57f4f052f45720fe5a9/utility_scripts/plugin_definitions/maintainers_validate.py#L36 which allowed this one get through "AutoIDM".lower() = "autoidm".lower() is true.

The maintainers_validate script was to check that all variant names exist in the maintainers.yml. If we remove the lowers in this comparison I think some could still pass if the user is consistently upper casing in the definition file and in maintainers.yml "AutoIDM" = "AutoIDM".

An example of others we've lower cased are `GtheSheep` -> [`gthesheep`](https://github.com/meltano/hub/blob/a599ea85c8569148214ae57f4f052f45720fe5a9/_data/meltano/extractors/tap-tvsquared/gthesheep.yml#L2).

What do you think about force all to be lower case using the JSON schema approach? I'm not a regex or json schema pro so it might be flakier than I imagine.

**Comment by edgarrmondragon** [comment]
> What do you think about force all to be lower case using the JSON schema approach? I'm not a regex or json schema pro so it might be flakier than I imagine.

@pnadolny13 regex for lowercase should be relatively easy.

> I think we added a CI check a while back to verify that the `variant` text is in the list of maintainers's IDs under maintainers.yml. Do I remember that correctly?

that sounds like something a `relationships` test in dbt could catch, but the LOE for getting the plugin data into a db (e.g. sqlite) might not be worth it 🤔.

**Comment by aaronsteers** [comment]
Added a simple check for case mismatches:

- https://github.com/meltano/hub/pull/982

Hopefully this catches them in CI so we other manipulations won't be necessary.

**Comment by aaronsteers** [comment]
That test is working. I put the casing fix into that PR as well: 

https://github.com/meltano/hub/pull/982#issuecomment-1295551764

**Comment by aaronsteers** [comment]
Confirmed the API docs_url is correct now: https://hub.meltano.com/meltano/api/v1/plugins/loaders/target-apprise--autoidm
