### ISSUE TITLE
bug: tap-abcfinancial fails to install

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#991]
This reference in the setup.py doesnt exist https://github.com/dmzobel/tap-abcfinancial/blob/6aad0894c0d8382841f3c855d312b447f842456c/setup.py#L15.

```
Running command git clone --filter=blob:none --quiet https://github.com/dmzobel/tap-abcfinancial.git /private/var/folders/x6/vstphn4x15l6wtw03s96ydyr0000gn/T/pip-req-build-y3vwjcrm
  Running command git clone --filter=blob:none --quiet https://github.com/dmzobel/tap-kit.git /private/var/folders/x6/vstphn4x15l6wtw03s96ydyr0000gn/T/pip-install-iz7tb2if/tap-kit_cd07ad1aa52848cd99bc1ae1de5b6ea8
  WARNING: Did not find branch or tag 'master', assuming revision or ref.
  Running command git checkout -q master
  error: pathspec 'master' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q master did not run successfully.
```

**Comment by edgarrmondragon** [comment]
Similar case to #993, default branch is now `main`

**Comment by pnadolny13** [comment]
Theres also another fork that might be better https://github.com/Radico/tap-abcfinancial

**Comment by pnadolny13** [comment]
Theres no obvious solution to this one without fixing the tap dependencies. The fork looks like the more recent version but it uses a private artifactory so it fails to install also. I'm inclined to hide this tap all together.
